# This is to test applications with subject-specific masks (e.g. volume data)
# In these applications, there could be elements with too many subjects with NaN (or generally, non-finite values) in .h5 file. We need to skip them and return NaN for these elements' stat.
# Test data was generated by this file: ModelArray_tests/testdata_ModelArray/prep_voxeldata_wNAs.Rmd
test_that("ModelArray handles subject-specific masks as expected", {
  
  check_as_expected <- function(df.results, expectedResults) {
    list.flag.same <- rep(FALSE, nrow(df.results))

    for (i in 1:nrow(df.results)) {
      the.expected.result <- expectedResults$flag_sufficient_subj[i]
      
      if (the.expected.result == 0) {    # insufficient subjects, expecting results as NaN
        list.flag.same[i] <- df.results[i,] %>% unlist() %>% is.nan() %>% all()     # expect: TRUE
      } else if (the.expected.result == 1) {
        list.flag.same[i] <- !(df.results[i,] %>% unlist() %>% is.nan()) %>% all()     # expect: TRUE
      }
        
    }
    
    list.flag.same
  }
  
  
  
  df.config <- data.frame(nsubj = c(60,40,30),
                          specials = c("", "", "allInvalidValues"))
  scalar_name <- "FA"
  
  
  for (i.config in 1:nrow(df.config)) {
    nsubj <- df.config$nsubj[i.config]
    specials <- df.config$specials[i.config]
    
    message(paste0("working on nsubj = ", toString(nsubj)))
    
    if (specials == "") {
      temp <- ""
    } else {
      temp <- paste0("_", specials)
    }
    fn.h5 <- system.file("extdata", 
                         paste0("n", toString(nsubj),"_voxels", temp, ".h5"), package = "ModelArray")
    fn.expectedResults <- gsub(".h5", "_expectedResults.txt", fn.h5)
    fn.csv <- gsub(".h5", ".csv", fn.h5)
    
    
    modelarray <- ModelArray(fn.h5, scalar_types = scalar_name)
    phenotypes <- read.csv(fn.csv)
    expectedResults <- read.csv(fn.expectedResults)
    
    if (specials == "") {   # specials=NULL
      mylm <- ModelArray.lm(FA ~ age, modelarray, phenotypes, scalar = scalar_name, element.subset = NULL)
      expect_equal(check_as_expected(mylm, expectedResults),
                   rep(TRUE, nrow(mylm)))
      
      mylm.fullOutputs <- ModelArray.lm(FA ~ age, modelarray, phenotypes, scalar = scalar_name, element.subset = NULL,
                                        full.outputs = TRUE, 
                                        correct.p.value.terms = c("fdr", "bonferroni"),correct.p.value.model = c("fdr", "bonferroni"))
      
      
      
    } else if (specials == "allInvalidValues") {  # if all NaNs
      expect_error(ModelArray.lm(FA ~ age, modelarray, phenotypes, scalar = scalar_name, element.subset = NULL))
    }
    
    
    # TODO: if threshold changes, expected results will also change, esp those around thr  
    
    # TODO: test the output messages are as expected
  }  
  
  

})