---
title: "demo for FixelArray.gam()"
output: html_document
---
```{r}
# set ups

# the working directory of this Demo is where it locates

flag_library_what <- "manually"   # "FixelArray" or "manually"

if (flag_library_what == "FixelArray") {
  message("run: devtools::install() to install FixelArray package")
  library(devtools)
  devtools::install()
  library(FixelArray)
  
  library(tictoc)
  
} else if (flag_library_what == "manually") {
  
  message("run: source several R scripts and library some R packages...")

  source("../R/FixelArray_Constructor.R")
  source("../R/FixelArray_S4Methods.R")
  source("../R/utils.R")
  source("../R/analyse.R")
  # library(FixelArray)
  suppressMessages(library(dplyr))
  library(broom)
  library(hdf5r)
  library(tictoc)
  library(mgcv)
  # library(lineprof)
  # library(profvis)
  # library(peakRAM)
  suppressMessages(library(doParallel))
}


flag_whichdataset <- "test_n50"   # "val" or "test_n50" or "josiane"
num.subj <- 50  # [integer]   
num.fixels <- 0  # 0 = full 
flag_which_subset <- ""
flag_where <- "vmware"   # "CUBIC" or "vmware"


```

# Load some fake data
```{r}

if (flag_whichdataset == "test_n50") {
  fn <- "../inst/extdata/n50_fixels.h5"
  
  if (flag_where == "CUBIC") {
    fn.output <- "../../dropbox/data_forCircleCI_n50/n50_fixels_output.h5"
  } else if (flag_where == "vmware") {
    fn.output <- "/home/chenying/Desktop/fixel_project/data/data_forCircleCI_n50/n50_fixels_output.h5"  
    # absoluate path: "/home/chenying/Desktop/fixel_project/data/data_forCircleCI_n50/n50_fixels_output.h5";  
    # relative path: "../../data/data_forCircleCI_n50/n50_fixels_output.h5"
  }
  
  fn_csv <- "../inst/extdata/n50_cohort.csv"
  
  scalar = c("FD")
  
}


# generate fn.output:
if (fn != fn.output) {
  file.copy(from=fn, to=fn.output, overwrite = TRUE, copy.mode = TRUE, copy.date = TRUE)   # , recursive = TRUE
}

# h5closeAll()
fixelarray <- FixelArray(fn.output, scalar_types = scalar)

```


A quick overview of this FixelArray object:
```{r}
fixelarray
scalars(fixelarray)[[scalar]]

# check # subjects matches:
if (dim(scalars(fixelarray)[[scalar]])[2] != num.subj) {
  stop(paste0("number of subjects in .h5 = ", dim(scalars(fixelarray)[[scalar]])[2], ", is not equal to entered number = ", toString(num.subj)))
}
```

We set up for performing linear regression (lm):
```{r}
phenotypes <- read.csv(fn_csv)
# check # subjects matches:
if (nrow(phenotypes) != num.subj) {
  stop(paste0("number of subjects in .csv = ", toString(nrow(phenotypes)), ", is not equal to entered number = ", toString(num.subj)))
}

if (flag_whichdataset == "test_n50") {
  formula <- FD ~ s(age) + sex         # ++++ to do: add motion quantification   # FD ~ s(age, k=4) + sex  # FD ~ s(age) + sex
} else if (flag_whichdataset == "val") {
  formula <- FD ~ Age
} else if (flag_whichdataset == "josiane") {
  formula <- FDC ~ Age
}

gam.method = "GCV.Cp"   # "GCV.Cp", "REML"  # any other methods usually used?
gam.optimizer = c("outer","newton")   # default: c("outer","newton") | # number of optimizers here will not change number of rows or columns in output gam model

fixel.subset <- 1:10
```

# Play around with mgcv::gam()
```{r}

i_fixel <- 1
values <- scalars(fixelarray)[[scalar]][i_fixel,]
dat <- phenotypes
dat[[scalar]] <- values

onemodel <- mgcv::gam(formula, data = dat,
                      method = gam.method,
                      optimizer = gam.optimizer)   # output of gam: see gamObject
onemodel.summary <- summary(onemodel)

onemodel.tidy.smoothTerms <- onemodel %>% broom::tidy()   #  !!! if formula is FD ~ age without s(), onemodel.tidy.smoothTerm will be empty....
onemodel.tidy.parametricTerms <- onemodel %>% broom::tidy(parametric = TRUE)  # different column names from .smoothTerm....

onemodel.glance <- onemodel %>% broom::glance()



onemodel.tidy.smoothTerms
onemodel.tidy.parametricTerms
onemodel.glance
onemodel.summary

# last two rows of output of summary():
onemodel.summary$r.sq   # adjusted r square
onemodel.summary$dev.expl   # Deviance explained
onemodel.summary$sp.criterion[["GCV.Cp"]]    # e.g. GCV when method is GCV    # test out other methods!
onemodel.summary$scale   # Scale est.

# for those values in summary() but not appear in onemodel.tidy or glance: see onemodel.summary and documentations of summary.gam()
# how to get the last two rows in summary(onemodel)? e.g. GCV (maybe other name), R-sq.(adj)

```

# Test out different conditions
```{r}
mygam_noSmooth <- FixelArray.gam(FD ~ age, data = fixelarray, phenotypes = phenotypes, scalar = scalar, fixel.subset = fixel.subset,
                                  n_cores = 2, pbar = FALSE) 
```