# This file provides the functions for model fitting of (all) elements


#' Fit linear model for element-wise data
#'
#' @description
#' `ModelArray.lm` fits linear model (`stats::lm()`) for each of elements requested, and returns a tibble
#' dataframe of requested model statistics.
#'
#' @details
#' You may request returning specific statistical variables by setting \code{var.*},
#' or you can get all by setting \code{full.outputs=TRUE}.
#' Note that statistics covered by \code{full.outputs} or \code{var.*} are the ones from broom::tidy()
#' and broom::glance() only, and do not include corrected p-values.
#' However FDR-corrected p-values ("fdr") are generated by default.
#' List of acceptable statistic names for each of \code{var.*}:
#' \itemize{
#'   \item \code{var.terms}: c("estimate","std.error","statistic","p.value");
#'      For interpretation please see \link[broom]{tidy.lm}.
#'   \item \code{var.model}: c("r.squared", "adj.r.squared", "sigma", "statistic",
#'      "p.value", "df", "logLik", "AIC", "BIC", "deviance", "df.residual", "nobs");
#'      For interpretation please see \link[broom]{glance.lm}.
#' }
#' For p-value corrections (arguments \code{correct.p.value.*}),
#' supported methods include all methods in `p.adjust.methods` except "none".
#' Can be more than one method. FDR-corrected p-values ("fdr") are calculated by default.
#' Turn it off by setting to "none". \cr
#' Arguments \code{num.subj.lthr.abs} and \code{num.subj.lthr.rel}
#' are mainly for input data with subject-specific masks,
#'  i.e. currently only for volume data. For fixel-wise data, you may ignore these arguments.
#'
#' @param formula Formula (passed to `stats::lm()`)
#' @param data ModelArray class
#' @param phenotypes A data.frame of the cohort with columns of independent variables
#' and covariates to be added to the model. It should contains a column called "source_file",
#' and this column should match to that in \code{data}.
#' @param scalar Optional character scalar name. If omitted, it is inferred from
#' the left-hand side of `formula`.
#' @param element.subset A list of positive integers (min = 1, max = number of elements).
#' The subset of elements you want to run. Default is `NULL`, i.e. requesting all elements in `data`.
#' @param full.outputs TRUE or FALSE, Whether to return full set of outputs.
#' If FALSE, it will only return those requested in arguments \code{var.*} and \code{correct.p.value.*};
#' if TRUE, arguments \code{var.*} will be ignored, and will return all possible statistics for
#' \code{var.*} and any options requested in arguments \code{correct.p.value.*}.
#' @param var.terms A list of characters.
#' The list of variables to save for terms (got from `broom::tidy()`).
#' See "Details" section for more.
#' @param var.model A list of characters.
#' The list of variables to save for the model (got from `broom::glance()`).
#' See "Details" section for more.
#' @param correct.p.value.terms A list of characters.
#' To perform and add a column for p.value correction for each term. Default: "fdr".
#' See "Details" section for more.
#' @param correct.p.value.model A list of characters.
#' To perform and add a column for p.value correction for the model.
#' Default: "fdr". See "Details" section for more.
#' @param num.subj.lthr.abs
#' An integer, lower threshold of absolute number of subjects.
#' For an element, if number of subjects who have finite values (defined by `is.finite()`,
#' i.e. not NaN or NA or Inf) in h5 file > \code{num.subj.lthr.abs},
#' then this element will be run normally; otherwise,
#' this element will be skipped and statistical outputs will be set as NaN.
#' Default is 10.
#' @param num.subj.lthr.rel A value between 0-1, lower threshold of relative number of subjects.
#' Similar to \code{num.subj.lthr.abs},
#' if proportion of subjects who have valid value > \code{num.subj.lthr.rel},
#' then this element will be run normally; otherwise,
#' this element will be skipped and statistical outputs will be set as NaN.
#' Default is 0.2.
#' @param verbose TRUE or FALSE, to print verbose message or not
#' @param pbar TRUE or FALSE, to print progress bar or not
#' @param n_cores Positive integer, The number of CPU cores to run with
#' @param on_error Character: one of "stop", "skip", or "debug". When an error occurs
#' while fitting an element, choose whether to stop, skip returning all-NaN values for
#' that element, or drop into `browser()` (if interactive) then skip. Default: "stop".
#' @param write_results_name Optional analysis name for incremental writes to
#' `results/<write_results_name>/results_matrix`.
#' @param write_results_file Optional HDF5 file path used when `write_results_name` is provided.
#' @param write_results_flush_every Positive integer number of elements per write block.
#' @param write_results_storage_mode Storage mode for results writes (e.g., `"double"`).
#' @param write_results_compression_level Gzip compression level (0-9) for results writes.
#' @param return_output If TRUE (default), return the combined data.frame. If FALSE,
#' returns `invisible(NULL)`; useful for streaming large runs to HDF5.
#' @param ... Additional arguments for `stats::lm()`
#' @return Tibble with the summarized model statistics for all elements requested
#' @importFrom dplyr %>%
#' @import doParallel
#' @import tibble
#' @importFrom stats p.adjust lm
#' @importFrom glue glue
#' @importFrom rlang :=
#' @export

ModelArray.lm <- function(formula, data, phenotypes, scalar = NULL, element.subset = NULL, full.outputs = FALSE,
                          var.terms = c("estimate", "statistic", "p.value"),
                          var.model = c("adj.r.squared", "p.value"),
                          correct.p.value.terms = c("fdr"), correct.p.value.model = c("fdr"),
                          num.subj.lthr.abs = 10, num.subj.lthr.rel = 0.2,
                          verbose = TRUE, pbar = TRUE, n_cores = 1,
                          on_error = "stop",
                          write_results_name = NULL,
                          write_results_file = NULL,
                          write_results_flush_every = 1000L,
                          write_results_storage_mode = "double",
                          write_results_compression_level = 4L,
                          return_output = TRUE,
                          ...) {
  .validate_modelarray_input(data)
  scalar <- .resolve_formula_scalar(formula, data, scalar)
  element.subset <- .validate_element_subset(element.subset, data, scalar)
  phenotypes <- .align_phenotypes(data, phenotypes, scalar)


  ### display additional arguments:
  dots <- list(...)
  dots_names <- names(dots)

  FUN <- stats::lm

  # subset:
  m1 <- "no default"
  printAdditionalArgu(FUN, "subset", dots, m1)

  # weights:
  m1 <- "no default"
  if ("weights" %in% dots_names) { # if user provides weights
    m_usr_input <- paste0(
      class(dots$weights),
      " with length of ",
      length(dots$weights)
    ) # message describing usr's input; cannot use dim on c(1,2)
  } else {
    m_usr_input <- NULL
  }
  printAdditionalArgu(FUN, "weights", dots, m1, m_usr_input)

  # na.action:
  m1 <- "no default"
  printAdditionalArgu(FUN, "na.action", dots, m1)

  # method:
  printAdditionalArgu(FUN, "method", dots) # default: "qr"

  # model:
  m1 <- invisible(eval(formals(FUN)[["model"]])) %>% as.character() # default: [logical] TRUE
  printAdditionalArgu(FUN, "model", dots, m1)

  # x:
  m1 <- invisible(eval(formals(FUN)[["x"]])) %>% as.character() # default: [logical] FALSE
  printAdditionalArgu(FUN, "x", dots, m1)

  # y:
  m1 <- invisible(eval(formals(FUN)[["y"]])) %>% as.character() # default: [logical] FALSE
  printAdditionalArgu(FUN, "y", dots, m1)

  # qr:
  m1 <- invisible(eval(formals(FUN)[["qr"]])) %>% as.character() # default: [logical] TRUE
  printAdditionalArgu(FUN, "qr", dots, m1)

  # singular.ok:
  m1 <- invisible(eval(formals(FUN)[["singular.ok"]])) %>% as.character() # default: [logical] TRUE
  printAdditionalArgu(FUN, "singular.ok", dots, m1)

  # contrasts:
  printAdditionalArgu(FUN, "contrasts", dots) # default: NULL

  # offset:
  m1 <- "no default" # there is no default
  printAdditionalArgu(FUN, "offset", dots, m1)


  num.subj.lthr <- .compute_subject_threshold(phenotypes, num.subj.lthr.abs, num.subj.lthr.rel)

  ### other setups:
  var.terms.full <- c("estimate", "std.error", "statistic", "p.value")
  var.model.full <- c(
    "r.squared", "adj.r.squared", "sigma", "statistic", "p.value",
    "df", "logLik", "AIC", "BIC", "deviance", "df.residual", "nobs"
  )
  if (full.outputs == TRUE) { # full set of outputs
    var.terms <- var.terms.full
    var.model <- var.model.full
  }
  # check on validity of list of vars:
  var.terms <- var.terms[!duplicated(var.terms)] # remove duplicated element(s)
  var.model <- var.model[!duplicated(var.model)]

  # check if all var.* are empty:
  if (length(var.terms) == 0 && length(var.model) == 0) {
    stop("All var.* arguments [var.terms, var.model] are empty!")
  }

  # check if every var is valid:
  for (var in var.terms) {
    if (!(var %in% var.terms.full)) {
      stop(paste0(var, " is not valid for var.terms!"))
    }
  }
  for (var in var.model) {
    if (!(var %in% var.model.full)) {
      stop(paste0(var, " is not valid for var.model!"))
    }
  }


  # check for p.value correction:
  # check for terms:
  check_validity_correctPValue(
    correct.p.value.terms, "correct.p.value.terms",
    var.terms, "var.terms"
  )
  # check for model:
  check_validity_correctPValue(
    correct.p.value.model, "correct.p.value.model",
    var.model, "var.model"
  )


  ### start the process:
  if (verbose) {
    message(glue::glue("Fitting element-wise linear models for {scalar}"))
    message(glue::glue("initiating...."))
  }

  num.elements.total <- numElementsTotal(modelarray = data, scalar_name = scalar)
  init_args <- list(
    formula = formula, modelarray = data, phenotypes = phenotypes, scalar = scalar,
    var.terms = var.terms, var.model = var.model,
    num.subj.lthr = num.subj.lthr, on_error = on_error, ...
  )
  initiator <- .find_initiator_element(
    analyseOneElement.lm, num.elements.total, init_args, verbose
  )
  column_names <- initiator$outputs$column_names
  list.terms <- initiator$outputs$list.terms
  num.stat.output <- length(column_names)

  if (verbose) {
    message(glue::glue("looping across elements...."))
  }

  need_term_correction <- (!all(correct.p.value.terms == "none")) && ("p.value" %in% var.terms)
  need_model_correction <- (!all(correct.p.value.model == "none")) && ("p.value" %in% var.model)
  need_full_df <- return_output || need_term_correction || need_model_correction
  if (!return_output && (need_term_correction || need_model_correction)) {
    stop("return_output=FALSE is not supported when p-value correction is requested")
  }

  writer <- .init_results_stream_writer(
    write_results_name = write_results_name,
    write_results_file = write_results_file,
    n_rows = length(element.subset),
    column_names = column_names,
    flush_every = write_results_flush_every,
    storage_mode = write_results_storage_mode,
    compression_level = write_results_compression_level
  )

  fits_all <- if (need_full_df) vector("list", length(element.subset)) else NULL
  chunk_size <- if (is.null(writer)) length(element.subset) else as.integer(write_results_flush_every)
  chunk_starts <- seq(1L, length(element.subset), by = chunk_size)
  for (chunk_start in chunk_starts) {
    chunk_end <- min(chunk_start + chunk_size - 1L, length(element.subset))
    chunk_elements <- element.subset[chunk_start:chunk_end]

    chunk_fits <- .parallel_dispatch(chunk_elements, analyseOneElement.lm, n_cores, pbar,
      formula = formula, modelarray = data, phenotypes = phenotypes, scalar = scalar,
      var.terms = var.terms, var.model = var.model,
      num.subj.lthr = num.subj.lthr, num.stat.output = num.stat.output,
      flag_initiate = FALSE, on_error = on_error,
      ...
    )

    if (need_full_df) {
      fits_all[chunk_start:chunk_end] <- chunk_fits
    }
    if (!is.null(writer)) {
      chunk_df <- as.data.frame(do.call(rbind, chunk_fits))
      colnames(chunk_df) <- column_names
      writer <- .results_stream_write_block(writer, chunk_df)
    }
  }
  .finalize_results_stream_writer(writer)

  if (!need_full_df) {
    return(invisible(NULL))
  }

  df_out <- do.call(rbind, fits_all)
  df_out <- as.data.frame(df_out)
  colnames(df_out) <- column_names

  df_out <- .correct_pvalues(df_out, list.terms, correct.p.value.terms, var.terms)
  df_out <- .correct_pvalues(df_out, "model", correct.p.value.model, var.model)

  # Streamed blocks were uncorrected; rewrite final corrected results if needed.
  if (!is.null(writer) && (need_term_correction || need_model_correction)) {
    writeResults(
      fn.output = write_results_file,
      df.output = df_out,
      analysis_name = write_results_name,
      overwrite = TRUE
    )
  }

  if (return_output) {
    return(df_out)
  }
  invisible(NULL)
}

#' Run GAM for element-wise data
#'
#' @description
#' `ModelArray.gam` fits gam model for each of elements requested,
#' and returns a tibble data.frame of requested model statistics.
#'
#' @details
#' You may request returning specific statistical variables by setting \code{var.*},
#' or you can get all by setting \code{full.outputs=TRUE}.
#' Note that statistics covered by \code{full.outputs} or
#' \code{var.*} are the ones from broom::tidy(), broom::glance(), and summary() only,
#' and do not include delta adjusted R-squared or partial R-squared or corrected p-values.
#' However FDR-corrected p-values ("fdr") are generated by default.
#'
#' List of acceptable statistic names for each of \code{var.*}:
#' \itemize{
#'  \item \code{var.smoothTerms}: c("edf","ref.df","statistic","p.value");
#'    For interpretation please see \link[broom]{tidy.gam} with `parametric=FALSE`.
#'  \item \code{var.parametricTerms}: c("estimate", "std.error","statistic","p.value");
#'    For interpretation please see \link[broom]{tidy.gam} with `parametric=TRUE`.
#'  \item \code{var.model}: c("adj.r.squared","dev.expl", "sp.criterion", "scale", "df",
#'    "logLik","AIC", "BIC", "deviance", "df.residual", "nobs"); "adj.r.squared" is \code{r.sq} from
#'    \link[mgcv]{summary.gam}; "sp.criterion" is \code{sp.criterion} from \link[mgcv]{summary.gam};
#'    For interpretation please see \link[broom]{glance.gam} and \link[mgcv]{summary.gam}.
#' }
#'
#' Regarding formula: So far these kinds of formula are tested:
#' \itemize{
#'   \item formula with smooth term, but without any interactions.
#'         Examples like \code{y ~ s(x) + orderedFactor}; \code{y ~ s(x) + s(z)}
#'   \item formula with interaction, but limited to only one interaction term, and in the formats of:
#'   \itemize{
#'       \item Formula #1: \code{y ~ orderedFactor + s(x) + s(x, by=orderedFactor) + other_covariate},
#'          where \code{orderedFactor} should be discrete variables and generated by `ordered`.
#'          The interaction term will be displayed as "s_x_BYorderedFactor"
#'          in the column name in returned data.frame.
#'          You may use function `gen_gamFormula_fxSmooth()` to generate one.
#'       \item Formula #2: \code{y ~ ti(x) + ti(z) + ti(x,z) + other_covariate},
#'          where \code{x} and \code{z} should be continuous variables.
#'          The interaction term will be displayed as "ti_x_z" in the column name in the returned data.frame.
#'          You may use function `gen_gamFormula_contIx()` to generate one.
#'   }
#' }
#' You may be interested in how important a term is in a model.
#' We provide two ways of quantification (see below).
#' Both of them require running the reduced model without this term of interest,
#' thus it will take longer time to run.
#' You can make such request via argument \code{changed.rsq.term.index}, and you'll get both quantifications.
#' \itemize{
#'   \item Delta adjusted R-squared (\code{delta.adj.rsq}) is defined as the difference between
#'      adjusted R-squared of full model (full formula in \code{formula}) and that of reduced model
#'      (formula without the term of interest). Notice that adjusted R-squared includes the penalty
#'      from the model complexity.
#'   \item Partial R-squared (\code{partial.rsq}) is defined as:
#'      \code{(sse.reduced.model - sse.full.model) / sse.reduced.model},
#'      where \code{sse} is the error sum of squares (or, residual sum of squares).
#'      It quantifies the amount of variance in the response variable that cannot be explained by the reduced model
#'      (model without term of interest), but can be explained by the term of interest in the full model.
#' }
#' \strong{___!!! WARNING !!!___}:
#' If you want to request \code{changed.rsq.term.index} for a term that has missing values,
#' before feeding \code{phenotypes} into \code{ModelArray.gam()},
#' you must exclude those observations (i.e., those rows in \code{phenotypes})
#' who have missing values in this term of interest from \code{phenotypes}.
#' You should do the same for each term you'd like to request in \code{changed.rsq.term.index},
#' if that term has missing values.
#' Without such exclusion, the full and reduced models would include different number of subjects,
#' causing inaccuracy of calculation of \code{delta.adj.rsq} and \code{partial.rsq}. \cr \cr
#' Other notes on \code{changed.rsq.term.index}:
#' \itemize{
#'   \item When requesting \code{changed.rsq.term.index},
#'      \code{fx} should be set as \code{TRUE}, so that degree of freedom is fixed.
#'   \item For formula with interactions, only formula in above formats are tested,
#'      and only the values of interaction term are valid.
#'      The delta.adj.rsq and partial.rsq for main effect (such as s(x) in Formula #1)
#'      may not "functionally" be these metrics, as their definitions should be changed to
#'      reduced formula without both main effect and interaction term.
#' }
#' For p-value corrections (arguments \code{correct.p.value.*}),
#' supported methods include all methods in `p.adjust.methods` except "none".
#' You can request more than one method. FDR-corrected p-values ("fdr") are calculated by default.
#' Turn it off by setting to "none".
#' Please notice that different from `ModelArray.lm`,
#' there is no p.value for the GAM model, so no "correct.p.value.model" for GAM model. \cr
#' Arguments \code{num.subj.lthr.abs} and \code{num.subj.lthr.rel}
#' are mainly for input data with subject-specific masks, i.e. currently only for volume data.
#' For fixel-wise data, you may ignore these arguments.
#'
#' @param formula Formula (passed to `mgcv::gam()`)
#' @param data ModelArray class
#' @param phenotypes A data.frame of the cohort with columns of independent variables and covariates
#' to be added to the model. It should contains a column called "source_file",
#' and this column should match to that in \code{data}.
#' @param scalar Optional character scalar name. If omitted, it is inferred from
#' the left-hand side of `formula`.
#' @param element.subset A list of positive integers (min = 1, max = number of elements).
#' The subset of elements you want to run. Default is `NULL`, i.e. requesting all elements in `data`.
#' @param full.outputs TRUE or FALSE, Whether to return full set of outputs.
#' If FALSE, it will only return those requested in arguments \code{var.*} and \code{correct.p.value.*};
#' if TRUE, arguments \code{var.*} will be ignored, and will return all possible statistics for \code{var.*}
#' and any options requested in arguments \code{correct.p.value.*}.
#' @param var.smoothTerms A list of characters.
#' The list of variables to save for smooth terms (got from `broom::tidy(parametric = FALSE)`).
#' Example smooth term: age in formula "outcome ~ s(age)". See "Details" section for more.
#' @param var.parametricTerms A list of characters.
#' The list of variables to save for parametric terms (got from `broom::tidy(parametric = TRUE)`).
#' Example parametric term: sex in formula "outcome ~ s(age) + sex".
#' See "Details" section for more.
#' @param var.model A list of characters.
#' The list of variables to save for the model (got from `broom::glance()` and `summary()`).
#' See "Details" section for more.
#' @param changed.rsq.term.index A list of (one or several) positive integers.
#' Each element in the list means the i-th term of the formula's right hand side
#' as the term of interest for changed R-squared between with and without it.
#' Both delta adjusted R-squared and partial R-squared will be calculated for each of term requested.
#' Usually term of interest is smooth term, or interaction term in models with interactions.
#'  See "Details" section for more, especially the "WARNING" in Details section for cases with caution!!
#' @param correct.p.value.smoothTerms A list of characters.
#' To perform and add a column for p.value correction for each smooth term.
#' Default: "fdr". See "Details" section for more.
#' @param correct.p.value.parametricTerms A list of characters.
#' To perform and add a column for p.value correction for each parametric term. Default: "fdr".
#' See "Details" section for more.
#' @param num.subj.lthr.abs An integer, lower threshold of absolute number of subjects.
#' For an element, if number of subjects who have finite values (defined by `is.finite()`,
#' i.e. not NaN or NA or Inf) in h5 file > \code{num.subj.lthr.abs},
#' then this element will be run normally;
#' otherwise, this element will be skipped and statistical outputs will be set as NaN.
#' Default is 10.
#' @param num.subj.lthr.rel A value between 0-1, lower threshold of relative number of subjects.
#' Similar to \code{num.subj.lthr.abs},
#' if proportion of subjects who have valid value > \code{num.subj.lthr.rel},
#' then this element will be run normally; otherwise,
#' this element will be skipped and statistical outputs will be set as NaN.
#' Default is 0.2.
#' @param verbose TRUE or FALSE, to print verbose messages or not
#' @param pbar TRUE or FALSE, to print progress bar or not
#' @param n_cores Positive integer, The number of CPU cores to run with
#' @param on_error Character: one of "stop", "skip", or "debug". When an error occurs
#' while fitting an element, choose whether to stop, skip returning all-NaN values for
#' that element, or drop into `browser()` (if interactive) then skip. Default: "stop".
#' @param write_results_name Optional analysis name for incremental writes to
#' `results/<write_results_name>/results_matrix`.
#' @param write_results_file Optional HDF5 file path used when `write_results_name` is provided.
#' @param write_results_flush_every Positive integer number of elements per write block.
#' @param write_results_storage_mode Storage mode for results writes (e.g., `"double"`).
#' @param write_results_compression_level Gzip compression level (0-9) for results writes.
#' @param return_output If TRUE (default), return the combined data.frame. If FALSE,
#' returns `invisible(NULL)`; useful for streaming large runs to HDF5.
#' @param ... Additional arguments for `mgcv::gam()`
#' @return Tibble with the summarized model statistics for all elements requested
#' @importFrom dplyr %>% mutate
#' @import doParallel
#' @import tibble
#' @import mgcv
#' @importFrom stats terms as.formula drop.terms p.adjust
#' @importFrom glue glue
#' @importFrom rlang :=
#' @export

ModelArray.gam <- function(formula, data, phenotypes, scalar = NULL, element.subset = NULL, full.outputs = FALSE,
                           var.smoothTerms = c("statistic", "p.value"),
                           var.parametricTerms = c("estimate", "statistic", "p.value"),
                           var.model = c("dev.expl"),
                           changed.rsq.term.index = NULL,
                           correct.p.value.smoothTerms = c("fdr"),
                           correct.p.value.parametricTerms = c("fdr"),
                           num.subj.lthr.abs = 10, num.subj.lthr.rel = 0.2,
                           verbose = TRUE, pbar = TRUE, n_cores = 1,
                           on_error = "stop",
                           write_results_name = NULL,
                           write_results_file = NULL,
                           write_results_flush_every = 1000L,
                           write_results_storage_mode = "double",
                           write_results_compression_level = 4L,
                           return_output = TRUE,
                           ...) {
  .validate_modelarray_input(data)
  scalar <- .resolve_formula_scalar(formula, data, scalar)
  element.subset <- .validate_element_subset(element.subset, data, scalar)

  # check if the formula is valid in terms of mgcv::gam()
  tryCatch(
    {
      gam.formula.breakdown <- mgcv::interpret.gam(formula)
    },
    error = function(cond) {
      stop(paste0("The formula is not valid for mgcv::gam()! Please check and revise."))
    }
  )

  checker_gam_formula(formula, gam.formula.breakdown)

  phenotypes <- .align_phenotypes(data, phenotypes, scalar)

  ### display additional arguments: [only important one]
  dots <- list(...)
  dots_names <- names(dots)

  FUN <- mgcv::gam

  # method: (default: "GCV.Cp")
  printAdditionalArgu(FUN, "method", dots) # default: "GCV.Cp"

  # TODO: optional: check if fx=FALSE; if so, add edf to the list of var + warning: fx=TRUE is recommended


  num.subj.lthr <- .compute_subject_threshold(phenotypes, num.subj.lthr.abs, num.subj.lthr.rel)

  ### when full.outputs = TRUE:
  var.smoothTerms.full <- c("edf", "ref.df", "statistic", "p.value")
  var.parametricTerms.full <- c("estimate", "std.error", "statistic", "p.value")
  var.model.full <- c(
    "adj.r.squared", "dev.expl", "sp.criterion", "scale",
    "df", "logLik", "AIC", "BIC", "deviance", "df.residual", "nobs"
  )

  if (full.outputs == TRUE) { # full set of outputs
    var.smoothTerms <- var.smoothTerms.full
    var.parametricTerms <- var.parametricTerms.full
    var.model <- var.model.full
  }

  ### check on validity of arguments: var.term and var.model
  var.smoothTerms <- var.smoothTerms[!duplicated(var.smoothTerms)] # remove duplicated element(s)
  var.parametricTerms <- var.parametricTerms[!duplicated(var.parametricTerms)]
  var.model <- var.model[!duplicated(var.model)]

  # check if all var.* are empty:
  if (length(var.smoothTerms) == 0 && length(var.parametricTerms) == 0 && length(var.model) == 0) {
    stop("All var.* arguments [var.smoothTerms, var.parametricTerms, var.model] are empty!")
  }

  # check if every var is valid:
  for (var in var.smoothTerms) {
    if (!(var %in% var.smoothTerms.full)) {
      stop(paste0(var, " is not valid for var.smoothTerms!"))
    }
  }
  for (var in var.parametricTerms) {
    if (!(var %in% var.parametricTerms.full)) {
      stop(paste0(var, " is not valid for var.parametricTerms!"))
    }
  }
  for (var in var.model) {
    if (!(var %in% var.model.full)) {
      stop(paste0(var, " is not valid!"))
    }
  }


  var.model.orig <- var.model
  if (!is.null(changed.rsq.term.index)) { # changed.rsq is not null --> requested

    # check if the term index is valid:
    if (min(changed.rsq.term.index) <= 0) {
      # any of not positive | can't really check if it's integer as is.integer(1) is FALSE...
      stop(
        paste0(
          "There is element(s) in changed.rsq.term.index <= 0. ",
          "It should be a (list of) positive integer!"
        )
      )
    }

    terms.full.formula <- stats::terms(formula, keep.order = TRUE)
    # not the re-order the terms | see: https://rdrr.io/r/stats/terms.formula.html
    if (max(changed.rsq.term.index) > length(labels(terms.full.formula))) {
      # if max is more than the number of terms on RHS of formula
      stop(
        paste0(
          "Largest index in changed.rsq.term.index is more than the term number on the ",
          "right hand side of formula!"
        )
      )
    }

    # check how many variables on RHS; if no (but intercept, i.e. xx ~ 1), stop
    if (length(labels(terms.full.formula)) == 0) {
      stop(
        paste0(
          "Trying to analyze changed.rsq but there is no variable (except intercept 1) ",
          "on right hand side of formula! Please provide at least one valid variable."
        )
      )
    }

    # print warning:
    message(
      paste0(
        "will get changed R-squared (delta.adj.rsq and partial.rsq) so the execution time ",
        "will be longer."
      )
    )
    # add adj.r.squared into var.model
    if (!("adj.r.squared" %in% var.model)) {
      var.model <- c(var.model, "adj.r.squared")
    }

    # also should return model.sse (for both full and reduced model):
    flag_sse <- TRUE
  } else { # changed.rsq is null --> not requested
    flag_sse <- FALSE # no need to calculate sse for the model
  }

  ### check on arguments: p-values correction methods
  # check for smoothTerms:
  check_validity_correctPValue(
    correct.p.value.smoothTerms, "correct.p.value.smoothTerms",
    var.smoothTerms, "var.smoothTerms"
  )
  # check for parametricTerms:
  check_validity_correctPValue(
    correct.p.value.parametricTerms, "correct.p.value.parametricTerms",
    var.parametricTerms, "var.parametricTerms"
  )


  ### run
  if (verbose) {
    message(glue::glue("Fitting element-wise GAMs for {scalar}"))
    message(glue::glue("initiating...."))
  }

  num.elements.total <- numElementsTotal(modelarray = data, scalar_name = scalar)
  init_args <- list(
    formula = formula, modelarray = data, phenotypes = phenotypes, scalar = scalar,
    var.smoothTerms = var.smoothTerms, var.parametricTerms = var.parametricTerms,
    var.model = var.model,
    num.subj.lthr = num.subj.lthr, flag_sse = flag_sse, on_error = on_error, ...
  )
  initiator <- .find_initiator_element(
    analyseOneElement.gam, num.elements.total, init_args, verbose
  )
  i_element_success_initiate <- initiator$i_element
  column_names <- initiator$outputs$column_names
  list.smoothTerms <- initiator$outputs$list.smoothTerms
  list.parametricTerms <- initiator$outputs$list.parametricTerms
  num.stat.output <- length(column_names)

  if (verbose) {
    message(glue::glue("looping across elements...."))
  }

  need_smooth_correction <- (!all(correct.p.value.smoothTerms == "none")) &&
    ("p.value" %in% var.smoothTerms)
  need_param_correction <- (!all(correct.p.value.parametricTerms == "none")) &&
    ("p.value" %in% var.parametricTerms)
  need_changed_rsq <- !is.null(changed.rsq.term.index)
  need_full_df <- return_output || need_smooth_correction || need_param_correction || need_changed_rsq
  if (!return_output && (need_smooth_correction || need_param_correction || need_changed_rsq)) {
    stop("return_output=FALSE is not supported when p-value correction or changed.rsq is requested")
  }

  writer <- .init_results_stream_writer(
    write_results_name = write_results_name,
    write_results_file = write_results_file,
    n_rows = length(element.subset),
    column_names = column_names,
    flush_every = write_results_flush_every,
    storage_mode = write_results_storage_mode,
    compression_level = write_results_compression_level
  )

  fits_all <- if (need_full_df) vector("list", length(element.subset)) else NULL
  chunk_size <- if (is.null(writer)) length(element.subset) else as.integer(write_results_flush_every)
  chunk_starts <- seq(1L, length(element.subset), by = chunk_size)
  for (chunk_start in chunk_starts) {
    chunk_end <- min(chunk_start + chunk_size - 1L, length(element.subset))
    chunk_elements <- element.subset[chunk_start:chunk_end]

    chunk_fits <- .parallel_dispatch(chunk_elements, analyseOneElement.gam, n_cores, pbar,
      formula = formula, modelarray = data, phenotypes = phenotypes, scalar = scalar,
      var.smoothTerms = var.smoothTerms, var.parametricTerms = var.parametricTerms,
      var.model = var.model,
      num.subj.lthr = num.subj.lthr, num.stat.output = num.stat.output,
      flag_initiate = FALSE, flag_sse = flag_sse, on_error = on_error,
      ...
    )

    if (need_full_df) {
      fits_all[chunk_start:chunk_end] <- chunk_fits
    }
    if (!is.null(writer)) {
      chunk_df <- as.data.frame(do.call(rbind, chunk_fits))
      colnames(chunk_df) <- column_names
      writer <- .results_stream_write_block(writer, chunk_df)
    }
  }
  .finalize_results_stream_writer(writer)

  if (!need_full_df) {
    return(invisible(NULL))
  }

  df_out <- do.call(rbind, fits_all)
  df_out <- as.data.frame(df_out)
  colnames(df_out) <- column_names


  ### get the changed.rsq for smooth terms:
  if (!is.null(changed.rsq.term.index)) { # if changed.rsq is requested
    message("Getting delta R-squared: running the reduced model...")

    # list of term of interest for changed.rsq:
    changed.rsq.term.fullFormat.list <- labels(terms.full.formula)[changed.rsq.term.index]
    # the term for changed.rsq, in full format
    # get the short version:
    changed.rsq.term.shortFormat.list <- list()
    for (changed.rsq.term.fullFormat in changed.rsq.term.fullFormat.list) {
      temp <- strsplit(changed.rsq.term.fullFormat, "[(]")[[1]]
      if (length(temp) == 1) { # it's not a smooth term - as there is no ()
        str_valid <- changed.rsq.term.fullFormat
      } else {
        smooth.class <- temp[1]

        theEval <- eval(parse(text = changed.rsq.term.fullFormat))
        str_valid <- paste0(
          smooth.class, "_",
          paste(theEval$term, collapse = "_")
        ) # ti(x,z) --> ti_x_z; s(x) --> s_x
        if (theEval$by != "NA") {
          str_valid <- paste0(str_valid, "_BY", theEval$by) # s(age,by=oSex) --> s_age_BYoSex
        }
      }

      changed.rsq.term.shortFormat <- str_valid
      changed.rsq.term.shortFormat.list <- append(changed.rsq.term.shortFormat.list, changed.rsq.term.shortFormat)
    }

    # loop of each changed.rsq.term.index (i.e. each term of interest)
    for (i.changed.rsq.term in seq_along(changed.rsq.term.fullFormat.list)) {
      idx.changed.rsq.term <- changed.rsq.term.index[i.changed.rsq.term] # index
      changed.rsq.term.fullFormat <- changed.rsq.term.fullFormat.list[i.changed.rsq.term]
      changed.rsq.term.shortFormat <- changed.rsq.term.shortFormat.list[[i.changed.rsq.term]][1] # it's nested

      # get the formula of reduced model
      # check if there is only one term (after removing it in reduced model,
      # there is no term but intercept in the formula...)
      if (length(labels(terms.full.formula)) == 1) {
        temp <- toString(formula) %>% strsplit("[, ]")
        reduced.formula <- stats::as.formula(paste0(temp[[1]][3], "~1"))
      } else {
        reduced.formula <- formula(
          stats::drop.terms(
            terms.full.formula,
            idx.changed.rsq.term,
            keep.response = TRUE
          )
        ) # index on RHS of formula -> change to class of formula (stats::as.formula does not work)
      }

      message(
        paste0(
          "* Getting changed R-squared for term: ",
          changed.rsq.term.fullFormat,
          " via reduced model as below",
          "; will show up as ",
          changed.rsq.term.shortFormat,
          " in final dataframe"
        )
      )
      print(reduced.formula)

      # var* for reduced model: only adjusted r sq is enough
      # initiate:
      reduced.model.outputs_initiator <- analyseOneElement.gam(
        i_element = i_element_success_initiate, # directly use the i_element with known success
        reduced.formula, data, phenotypes, scalar,
        var.smoothTerms = c(), var.parametricTerms = c(), var.model = c("adj.r.squared"),
        num.subj.lthr = num.subj.lthr, num.stat.output = NULL,
        flag_initiate = TRUE, flag_sse = TRUE, # also to get model.sse
        ...
      )
      reduced.model.column_names <- reduced.model.outputs_initiator$column_names
      reduced.model.num.stat.output <- length(reduced.model.column_names)

      reduced.model.fits <- .parallel_dispatch(
        element.subset, analyseOneElement.gam, n_cores, pbar,
        formula = reduced.formula, modelarray = data, phenotypes = phenotypes,
        scalar = scalar,
        var.smoothTerms = c(), var.parametricTerms = c(),
        var.model = c("adj.r.squared"),
        num.subj.lthr = num.subj.lthr,
        num.stat.output = reduced.model.num.stat.output,
        flag_initiate = FALSE, flag_sse = TRUE,
        ...
      )

      reduced.model.df_out <- do.call(rbind, reduced.model.fits)
      reduced.model.df_out <- as.data.frame(reduced.model.df_out)
      colnames(reduced.model.df_out) <- reduced.model.column_names

      # rename "adj.r.squared" as "redModel.adj.r.squared" before merging into df_out
      names(reduced.model.df_out)[names(reduced.model.df_out) == "model.adj.r.squared"] <- "redModel.adj.r.squared"
      # rename "model.sse" as "redModel.sse" before merging into df_out
      names(reduced.model.df_out)[names(reduced.model.df_out) == "model.sse"] <- "redModel.sse"

      # combine new df_out to original one:
      df_out <- merge(df_out, reduced.model.df_out, by = "element_id")

      # calculate the delta.adj.rsq, add to the df_out:
      df_out <- df_out %>% dplyr::mutate(
        "{changed.rsq.term.shortFormat}.delta.adj.rsq" := model.adj.r.squared - redModel.adj.r.squared
      ) # calculate the partial.rsq, add to the df_out:
      df_out <- df_out %>% dplyr::mutate(
        "{changed.rsq.term.shortFormat}.partial.rsq" := (redModel.sse - model.sse) / redModel.sse
      ) # partialRsq <- (sse.red - sse.full) / sse.red


      # remove column of redModel
      df_out <- df_out %>% subset(select = -c(
        redModel.adj.r.squared,
        redModel.sse
      ))
    } # end of for loop across term of interest for changed.rsq


    # if adjusted r sq is not requested (see var.model.orig), remove it:
    if (!("adj.r.squared" %in% var.model.orig)) {
      df_out <- df_out %>% subset(select = -c(model.adj.r.squared))
    }

    # remove full model's sse (model.sse):
    df_out <- df_out %>% subset(select = -c(model.sse))
  } # end of if: requesting changed.rsq


  ### correct p values
  df_out <- .correct_pvalues(df_out, list.smoothTerms, correct.p.value.smoothTerms, var.smoothTerms)
  df_out <- .correct_pvalues(
    df_out, list.parametricTerms, correct.p.value.parametricTerms, var.parametricTerms
  )

  if (!is.null(writer) && (need_smooth_correction || need_param_correction || need_changed_rsq)) {
    writeResults(
      fn.output = write_results_file,
      df.output = df_out,
      analysis_name = write_results_name,
      overwrite = TRUE
    )
  }

  ### return
  if (return_output) {
    return(df_out)
  }
  invisible(NULL)
}


#' Run a user-supplied function for element-wise data
#'
#' @description
#' `ModelArray.wrap` runs a user-supplied function `FUN` for each requested element and
#' returns a tibble/data.frame of results combined across elements.
#'
#' @details
#' This provides a generic framework reusing ModelArray's per-element looping, alignment,
#' subject-thresholding, and parallelization. The user function will be called as
#' `FUN(data = dat, ...)` where `dat` is `phenotypes` with the response column named `scalar`
#' appended for the current element. The return value from `FUN` for a single element must be
#' either a one-row data.frame/tibble, a named list, or a named atomic vector. The column
#' names from the first successful element determine the final schema.
#'
#' Note: `ModelArray.wrap` never performs any p-value corrections or modifications.
#' If you need adjusted p-values (e.g., FDR), implement them inside your provided `FUN`.
#'
#' @param FUN A function that accepts at least `data` and returns a one-row data.frame/tibble,
#' a named list, or a named vector of results for that element.
#' @param data ModelArray class
#' @param phenotypes A data.frame with cohort covariates; must contain column `source_file`.
#' It must match `sources(data)[[scalar]]` order and contents (reordered if needed).
#' @param scalar Character, the scalar name to analyze
#' @param element.subset Optional integer vector of element indices (1-based); defaults to all
#' @param num.subj.lthr.abs Integer lower threshold for subjects with finite values (default 10)
#' @param num.subj.lthr.rel Relative lower threshold (0-1) (default 0.2)
#' @param verbose TRUE/FALSE to print messages
#' @param pbar TRUE/FALSE to show progress bar
#' @param n_cores Positive integer number of CPU cores
#' @param on_error Character: one of "stop", "skip", or "debug". When an error occurs in
#' the user function for an element, choose whether to stop, skip returning all-NaN values
#' for that element, or drop into `browser()` (if interactive) then skip. Default: "stop".
#' @param write_scalar_name Optional character scalar name. If provided, `ModelArray.wrap`
#' writes selected output columns into `scalars/<write_scalar_name>/values` while processing.
#' @param write_scalar_file Optional character HDF5 output filename used when
#' `write_scalar_name` is provided.
#' @param write_scalar_columns Optional character/integer selector for output columns to save
#' as scalar values. If NULL, uses all wrap output columns except `element_id`.
#' @param write_scalar_column_names Optional character vector of source names saved as
#' scalar `column_names`. If NULL, uses `phenotypes$source_file`.
#' @param write_scalar_flush_every Positive integer number of elements per write block.
#' @param write_scalar_storage_mode Storage mode for scalar writes (e.g., `"double"`).
#' @param write_scalar_compression_level Gzip compression level (0-9) for scalar writes.
#' @param write_results_name Optional analysis name for incremental writes to
#' `results/<write_results_name>/results_matrix`.
#' @param write_results_file Optional HDF5 file path used when `write_results_name` is provided.
#' @param write_results_flush_every Positive integer number of elements per write block for
#' results writes.
#' @param write_results_storage_mode Storage mode for results writes (e.g., `"double"`).
#' @param write_results_compression_level Gzip compression level (0-9) for results writes.
#' @param return_output If TRUE (default), return the combined data.frame. If FALSE,
#' returns `invisible(NULL)`; useful when writing large outputs directly to HDF5.
#' @param ... Additional arguments forwarded to `FUN`
#' @return Tibble/data.frame with one row per element and first column `element_id`
#' @importFrom dplyr %>%
#' @import doParallel
#' @import tibble
#' @importFrom glue glue
#' @export
ModelArray.wrap <- function(FUN, data, phenotypes, scalar, element.subset = NULL,
                            num.subj.lthr.abs = 10, num.subj.lthr.rel = 0.2,
                            verbose = TRUE, pbar = TRUE, n_cores = 1,
                            on_error = "stop",
                            write_scalar_name = NULL,
                            write_scalar_file = NULL,
                            write_scalar_columns = NULL,
                            write_scalar_column_names = NULL,
                            write_scalar_flush_every = 1000L,
                            write_scalar_storage_mode = "double",
                            write_scalar_compression_level = 4L,
                            write_results_name = NULL,
                            write_results_file = NULL,
                            write_results_flush_every = 1000L,
                            write_results_storage_mode = "double",
                            write_results_compression_level = 4L,
                            return_output = TRUE,
                            ...) {
  .validate_modelarray_input(data)
  element.subset <- .validate_element_subset(element.subset, data, scalar)
  phenotypes <- .align_phenotypes(data, phenotypes, scalar)
  num.subj.lthr <- .compute_subject_threshold(phenotypes, num.subj.lthr.abs, num.subj.lthr.rel)

  ### initiate to get column names
  if (verbose) {
    message(glue::glue("Running element-wise user function for {scalar}"))
    message(glue::glue("initiating...."))
  }

  num.elements.total <- numElementsTotal(modelarray = data, scalar_name = scalar)
  init_args <- list(
    user_fun = FUN, modelarray = data, phenotypes = phenotypes, scalar = scalar,
    num.subj.lthr = num.subj.lthr, on_error = on_error, ...
  )
  initiator <- .find_initiator_element(
    analyseOneElement.wrap, num.elements.total, init_args, verbose
  )
  column_names <- initiator$outputs$column_names
  num.stat.output <- length(column_names)

  if (verbose) message(glue::glue("looping across elements...."))

  writer_results <- .init_results_stream_writer(
    write_results_name = write_results_name,
    write_results_file = write_results_file,
    n_rows = length(element.subset),
    column_names = column_names,
    flush_every = write_results_flush_every,
    storage_mode = write_results_storage_mode,
    compression_level = write_results_compression_level
  )

  writing_scalar <- !is.null(write_scalar_name)
  if (writing_scalar) {
    if (!is.character(write_scalar_name) || length(write_scalar_name) != 1L || write_scalar_name == "") {
      stop("write_scalar_name must be a non-empty character string when provided")
    }
    if (is.null(write_scalar_file) || !is.character(write_scalar_file) || length(write_scalar_file) != 1L) {
      stop("write_scalar_file must be a single character path when write_scalar_name is provided")
    }
    if (!is.numeric(write_scalar_flush_every) || length(write_scalar_flush_every) != 1L || write_scalar_flush_every <= 0) {
      stop("write_scalar_flush_every must be a positive integer")
    }
    write_scalar_flush_every <- as.integer(write_scalar_flush_every)

    if (is.null(write_scalar_columns)) {
      write_scalar_columns <- setdiff(column_names, "element_id")
    }

    if (is.character(write_scalar_columns)) {
      missing_cols <- setdiff(write_scalar_columns, column_names)
      if (length(missing_cols) > 0L) {
        stop(
          "write_scalar_columns not found in wrap output: ",
          paste(missing_cols, collapse = ", ")
        )
      }
      scalar_col_idx <- match(write_scalar_columns, column_names)
    } else if (is.numeric(write_scalar_columns)) {
      scalar_col_idx <- as.integer(write_scalar_columns)
      if (any(scalar_col_idx < 1L) || any(scalar_col_idx > length(column_names))) {
        stop("write_scalar_columns numeric indices are out of bounds")
      }
    } else {
      stop("write_scalar_columns must be NULL, character, or integer")
    }

    scalar_col_names <- column_names[scalar_col_idx]
    if (length(scalar_col_names) == 0L) {
      stop("write_scalar_columns selected zero columns")
    }

    if (is.null(write_scalar_column_names)) {
      write_scalar_column_names <- as.character(phenotypes[["source_file"]])
    } else {
      write_scalar_column_names <- as.character(write_scalar_column_names)
    }
    if (length(write_scalar_column_names) != length(scalar_col_idx)) {
      stop("length(write_scalar_column_names) must equal number of selected write_scalar_columns")
    }

    # Initialize scalar output dataset.
    if (!file.exists(write_scalar_file)) {
      rhdf5::h5createFile(write_scalar_file)
    }
    scalar_grp <- paste0("scalars/", write_scalar_name)
    h5_write <- hdf5r::H5File$new(write_scalar_file, mode = "a")
    if (!h5_write$exists("scalars")) {
      h5_write$create_group("scalars")
    }
    scalars_grp_obj <- h5_write$open("scalars")
    if (scalars_grp_obj$exists(write_scalar_name)) {
      scalars_grp_obj$link_delete(write_scalar_name)
    }
    scalars_grp_obj$create_group(write_scalar_name)
    h5_write$close_all()

    dataset_path <- paste0(scalar_grp, "/values")
    chunk_rows <- min(write_scalar_flush_every, length(element.subset))
    rhdf5::h5createDataset(
      file = write_scalar_file,
      dataset = dataset_path,
      dims = c(length(element.subset), length(scalar_col_idx)),
      storage.mode = write_scalar_storage_mode,
      chunk = c(chunk_rows, length(scalar_col_idx)),
      level = as.integer(write_scalar_compression_level)
    )
  }

  fits_all <- if (return_output) vector("list", length(element.subset)) else NULL
  write_row_cursor <- 1L

  chunk_size <- length(element.subset)
  if (writing_scalar) {
    chunk_size <- min(chunk_size, write_scalar_flush_every)
  }
  if (!is.null(writer_results)) {
    chunk_size <- min(chunk_size, as.integer(write_results_flush_every))
  }
  chunk_starts <- seq(1L, length(element.subset), by = chunk_size)
  for (chunk_start in chunk_starts) {
    chunk_end <- min(chunk_start + chunk_size - 1L, length(element.subset))
    chunk_elements <- element.subset[chunk_start:chunk_end]

    chunk_fits <- .parallel_dispatch(chunk_elements, analyseOneElement.wrap, n_cores, pbar,
      user_fun = FUN, modelarray = data, phenotypes = phenotypes, scalar = scalar,
      num.subj.lthr = num.subj.lthr, num.stat.output = num.stat.output,
      flag_initiate = FALSE, on_error = on_error,
      ...
    )

    if (return_output) {
      fits_all[chunk_start:chunk_end] <- chunk_fits
    }

    chunk_df <- NULL
    if (!is.null(writer_results) || writing_scalar) {
      chunk_df <- as.data.frame(do.call(rbind, chunk_fits))
      colnames(chunk_df) <- column_names
    }
    if (!is.null(writer_results)) {
      writer_results <- .results_stream_write_block(writer_results, chunk_df)
    }

    if (writing_scalar) {
      block <- as.matrix(chunk_df[, scalar_col_idx, drop = FALSE])
      row_idx <- write_row_cursor:(write_row_cursor + nrow(block) - 1L)
      rhdf5::h5write(
        obj = block,
        file = write_scalar_file,
        name = dataset_path,
        index = list(row_idx, seq_len(ncol(block)))
      )
      write_row_cursor <- write_row_cursor + nrow(block)
    }
  }

  if (writing_scalar) {
    rhdf5::h5writeAttribute(
      attr = write_scalar_column_names,
      h5obj = write_scalar_file,
      name = "column_names",
      h5loc = dataset_path
    )
    rhdf5::h5write(
      obj = write_scalar_column_names,
      file = write_scalar_file,
      name = paste0("scalars/", write_scalar_name, "/column_names")
    )
    rhdf5::h5closeAll()
  }
  .finalize_results_stream_writer(writer_results)

  if (!return_output) {
    return(invisible(NULL))
  }

  df_out <- do.call(rbind, fits_all)
  df_out <- as.data.frame(df_out)
  colnames(df_out) <- column_names
  df_out
}
