#' Fit element-wise linear models
#'
#' @description
#' `ModelArray.lm` fits a linear model at each requested element in a
#' \linkS4class{ModelArray} and returns a tibble of requested model statistics.
#'
#' @details
#' You may request returning specific statistical variables by setting
#' \code{var.*}, or you can get all by setting \code{full.outputs = TRUE}.
#' Note that statistics covered by \code{full.outputs} or \code{var.*} are
#' the ones from \code{broom::tidy()}, \code{broom::glance()} only, and do
#' not include corrected p-values. However FDR-corrected p-values
#' (\code{"fdr"}) are generated by default.
#'
#' List of acceptable statistic names for each of \code{var.*}:
#' \itemize{
#'   \item \code{var.terms}: \code{c("estimate", "std.error", "statistic",
#'     "p.value")}; For interpretation please see \link[broom]{tidy.lm}.
#'   \item \code{var.model}: \code{c("r.squared", "adj.r.squared", "sigma",
#'     "statistic", "p.value", "df", "logLik", "AIC", "BIC", "deviance",
#'     "df.residual", "nobs")}; For interpretation please see
#'     \link[broom]{glance.lm}.
#' }
#'
#' For p-value corrections (arguments \code{correct.p.value.*}), supported
#' methods include all methods in \code{p.adjust.methods} except
#' \code{"none"}. You can request more than one method. FDR-corrected
#' p-values (\code{"fdr"}) are calculated by default. Turn it off by
#' setting to \code{"none"}.
#'
#' Arguments \code{num.subj.lthr.abs} and \code{num.subj.lthr.rel} are
#' mainly for input data with subject-specific masks, i.e. currently only
#' for volume data. For fixel-wise data, you may ignore these arguments.
#'
#' @param formula Formula (passed to \code{\link[stats]{lm}}).
#' @param data A \linkS4class{ModelArray} object.
#' @param phenotypes A data.frame of the cohort with columns of independent
#'   variables and covariates to be added to the model. It must contain a
#'   column called \code{"source_file"} whose entries match those in
#'   \code{sources(data)[[scalar]]}.
#' @param scalar Character. The name of the element-wise scalar to analyse.
#'   Must be one of \code{names(scalars(data))}.
#' @param element.subset Integer vector of element indices (1-based) to run.
#'   Default is \code{NULL}, i.e. all elements in \code{data}.
#' @param full.outputs Logical. If \code{TRUE}, return the full set of
#'   statistics (ignoring \code{var.*} arguments). If \code{FALSE} (default),
#'   only return those requested in \code{var.*} and
#'   \code{correct.p.value.*}.
#' @param var.terms Character vector. Statistics to save per term, from
#'   \code{broom::tidy()}. See Details.
#' @param var.model Character vector. Statistics to save for the overall
#'   model, from \code{broom::glance()}. See Details.
#' @param correct.p.value.terms Character vector. P-value correction
#'   method(s) for each term. Default: \code{"fdr"}. See Details.
#' @param correct.p.value.model Character vector. P-value correction
#'   method(s) for the model-level p-value. Default: \code{"fdr"}.
#'   See Details.
#' @param num.subj.lthr.abs Integer. Lower threshold for the absolute
#'   number of subjects with finite scalar values (not \code{NaN},
#'   \code{NA}, or \code{Inf}) required per element. Elements below this
#'   threshold are skipped (outputs set to \code{NaN}). Default is 10.
#' @param num.subj.lthr.rel Numeric between 0 and 1. Lower threshold for
#'   the proportion of subjects with finite values. Used together with
#'   \code{num.subj.lthr.abs} (the effective threshold is the maximum of
#'   the two). Default is 0.2.
#' @param verbose Logical. Print progress messages. Default \code{TRUE}.
#' @param pbar Logical. Show progress bar. Default \code{TRUE}.
#' @param n_cores Positive integer. Number of CPU cores for parallel
#'   processing via \code{\link[parallel]{mclapply}}. Default is 1
#'   (serial).
#' @param on_error Character: one of \code{"stop"}, \code{"skip"}, or
#'   \code{"debug"}. When an error occurs fitting one element: \code{"stop"}
#'   halts execution; \code{"skip"} returns all-\code{NaN} for that element;
#'   \code{"debug"} drops into \code{\link{browser}} (if interactive) then
#'   skips. Default: \code{"stop"}.
#' @param write_results_name Optional character. If provided, results are
#'   incrementally written to
#'   \code{results/<write_results_name>/results_matrix} in the HDF5 file
#'   specified by \code{write_results_file}.
#' @param write_results_file Optional character. HDF5 file path for
#'   incremental result writes. Required when \code{write_results_name}
#'   is provided.
#' @param write_results_flush_every Positive integer. Number of elements
#'   per write block. Default 1000.
#' @param write_results_storage_mode Character. Storage mode for HDF5
#'   writes (e.g. \code{"double"}). Default \code{"double"}.
#' @param write_results_compression_level Integer 0--9. Gzip compression
#'   level for HDF5 writes. Default 4.
#' @param return_output Logical. If \code{TRUE} (default), return the
#'   combined data.frame. If \code{FALSE}, return \code{invisible(NULL)};
#'   useful when writing large outputs directly to HDF5.
#' @param ... Additional arguments passed to \code{\link[stats]{lm}}.
#'
#' @return A tibble with one row per element. The first column is
#'   \code{element_id} (0-based). Remaining columns contain the requested
#'   statistics, named as \code{<term>.<statistic>} for per-term statistics
#'   and \code{model.<statistic>} for model-level statistics. If p-value
#'   corrections were requested, additional columns are appended with the
#'   correction method as suffix (e.g. \code{<term>.p.value.fdr}).
#'
#' @seealso \code{\link{ModelArray.gam}} for generalized additive models,
#'   \code{\link{ModelArray.wrap}} for user-supplied functions,
#'   \linkS4class{ModelArray} for the input class,
#'   \code{\link{ModelArray}} for the constructor,
#'   \code{\link{exampleElementData}} for testing formulas on a single
#'   element.
#'
#' @examplesIf interactive()
#' ma <- ModelArray("path/to/data.h5", scalar_types = c("FD"))
#' phenotypes <- read.csv("cohort.csv")
#'
#' # Fit linear model with default outputs
#' results <- ModelArray.lm(
#'   FD ~ age + sex,
#'   data = ma,
#'   phenotypes = phenotypes,
#'   scalar = "FD"
#' )
#' head(results)
#'
#' # Full outputs, no p-value correction
#' results_full <- ModelArray.lm(
#'   FD ~ age + sex,
#'   data = ma,
#'   phenotypes = phenotypes,
#'   scalar = "FD",
#'   full.outputs = TRUE,
#'   correct.p.value.terms = "none",
#'   correct.p.value.model = "none"
#' )
#'
#' @rdname ModelArray.lm
#' @export

ModelArray.lm <- function(formula, data, phenotypes, scalar = NULL, element.subset = NULL, full.outputs = FALSE,
                          var.terms = c("estimate", "statistic", "p.value"),
                          var.model = c("adj.r.squared", "p.value"),
                          correct.p.value.terms = c("fdr"),
                          correct.p.value.model = c("fdr"),
                          num.subj.lthr.abs = 10, num.subj.lthr.rel = 0.2,
                          verbose = TRUE, pbar = TRUE, n_cores = 1,
                          on_error = "stop",
                          write_results_name = NULL,
                          write_results_file = NULL,
                          write_results_flush_every = 1000L,
                          write_results_storage_mode = "double",
                          write_results_compression_level = 4L,
                          return_output = TRUE,
                          ...) {
  # Validation ----
  .validate_modelarray_input(data)

  if (is.null(scalar)){
    scalar <- .resolve_formula_scalar(formula, data, scalar)
  }

  element.subset <- .validate_element_subset(element.subset, data, scalar)
  phenotypes <- .align_phenotypes(data, phenotypes, scalar)

  # Display additional arguments ----
  dots <- list(...)
  dots_names <- names(dots)
  FUN <- stats::lm
  m1 <- "no default"
  printAdditionalArgu(FUN, "subset", dots, m1)
  m1 <- "no default"
  if ("weights" %in% dots_names) {
    m_usr_input <- paste0(class(dots$weights), " with length of ", length(dots$weights))
  } else {
    m_usr_input <- NULL
  }
  printAdditionalArgu(FUN, "weights", dots, m1, m_usr_input)
  m1 <- "no default"
  printAdditionalArgu(FUN, "na.action", dots, m1)
  printAdditionalArgu(FUN, "method", dots)
  m1 <- invisible(eval(formals(FUN)[["model"]])) %>% as.character()
  printAdditionalArgu(FUN, "model", dots, m1)
  m1 <- invisible(eval(formals(FUN)[["x"]])) %>% as.character()
  printAdditionalArgu(FUN, "x", dots, m1)

  num.subj.lthr <- .compute_subject_threshold(phenotypes, num.subj.lthr.abs, num.subj.lthr.rel)

  # Full outputs override ----
  var.terms.full <- c("estimate", "std.error", "statistic", "p.value")
  var.model.full <- c(
    "r.squared", "adj.r.squared", "sigma", "statistic", "p.value",
    "df", "logLik", "AIC", "BIC", "deviance", "df.residual", "nobs"
  )
  if (full.outputs == TRUE) {
    var.terms <- var.terms.full
    var.model <- var.model.full
  }

  # check on validity of list of vars:
  var.terms <- var.terms[!duplicated(var.terms)]
  var.model <- var.model[!duplicated(var.model)]

  # check if all var.* are empty:
  if (length(var.terms) == 0 && length(var.model) == 0) {
    stop("All var.* arguments [var.terms, var.model] are empty!")
  }

  # check if every var is valid:
  for (var in var.terms) {
    if (!(var %in% var.terms.full)) {
      stop(paste0(var, " is not valid for var.terms!"))
    }
  }
  for (var in var.model) {
    if (!(var %in% var.model.full)) {
      stop(paste0(var, " is not valid for var.model!"))
    }
  }

  # P-value correction checks ----
  check_validity_correctPValue(
    correct.p.value.terms, "correct.p.value.terms",
    var.terms, "var.terms"
  )
  check_validity_correctPValue(
    correct.p.value.model, "correct.p.value.model",
    var.model, "var.model"
  )

  # Build context ONCE before the loop ----
  ctx <- .build_lm_context(formula, data, phenotypes, scalar)

  # Start the model fitting ----
  if (verbose) {
    message(glue::glue("Fitting element-wise linear models for {scalar}"))
    message(glue::glue("initiating...."))
  }

  num.elements.total <- numElementsTotal(modelarray = data, scalar_name = scalar)

  # Initiate using ctx ----
  init_args <- list(
    ctx = ctx,
    var.terms = var.terms, var.model = var.model,
    num.subj.lthr = num.subj.lthr, on_error = on_error, ...
  )
  initiator <- .find_initiator_element(
    analyseOneElement.lm, num.elements.total, init_args, verbose
  )
  column_names <- initiator$outputs$column_names
  list.terms <- initiator$outputs$list.terms
  num.stat.output <- length(column_names)

  if (verbose) {
    message(glue::glue("looping across elements...."))
  }

  need_term_correction <- (!all(correct.p.value.terms == "none")) &&
    ("p.value" %in% var.terms)
  need_model_correction <- (!all(correct.p.value.model == "none")) &&
    ("p.value" %in% var.model)
  need_full_df <- return_output || need_term_correction || need_model_correction
  if (!return_output && (need_term_correction || need_model_correction)) {
    stop("return_output=FALSE is not supported when p-value correction is requested")
  }

  # Initialize stream writer ----
  writer <- .init_results_stream_writer(
    write_results_name = write_results_name,
    write_results_file = write_results_file,
    n_rows = length(element.subset),
    column_names = column_names,
    flush_every = write_results_flush_every,
    storage_mode = write_results_storage_mode,
    compression_level = write_results_compression_level
  )

  # Start model looping ----
  fits_all <- if (need_full_df) vector("list", length(element.subset)) else NULL
  chunk_size <- if (is.null(writer)) length(element.subset) else as.integer(write_results_flush_every)
  chunk_starts <- seq(1L, length(element.subset), by = chunk_size)

  for (chunk_start in chunk_starts) {
    chunk_end <- min(chunk_start + chunk_size - 1L, length(element.subset))
    chunk_elements <- element.subset[chunk_start:chunk_end]

    ## Main loop now passes ctx instead of formula/modelarray/phenotypes/scalar
    chunk_fits <- .parallel_dispatch(
      chunk_elements, analyseOneElement.lm, n_cores, pbar,
      ctx = ctx,
      var.terms = var.terms, var.model = var.model,
      num.subj.lthr = num.subj.lthr, num.stat.output = num.stat.output,
      flag_initiate = FALSE, on_error = on_error,
      ...
    )

    if (need_full_df) {
      fits_all[chunk_start:chunk_end] <- chunk_fits
    }
    if (!is.null(writer)) {
      chunk_df <- as.data.frame(do.call(rbind, chunk_fits))
      colnames(chunk_df) <- column_names
      writer <- .results_stream_write_block(writer, chunk_df)
    }
  }
  .finalize_results_stream_writer(writer)

  if (!need_full_df) {
    return(invisible(NULL))
  }

  result_mat <- do.call(rbind, fits_all)
  col_list <- lapply(seq_len(ncol(result_mat)), function(j) result_mat[, j])
  names(col_list) <- column_names
  df_out <- cheapr::fast_df(.args = col_list)

  df_out <- .correct_pvalues(df_out, list.terms, correct.p.value.terms, var.terms)
  df_out <- .correct_pvalues(df_out, "model", correct.p.value.model, var.model)

  # Rewrite corrected results to HDF5 if needed ----
  if (!is.null(writer) && (need_term_correction || need_model_correction)) {
    writeResults(
      fn.output = write_results_file,
      df.output = df_out,
      analysis_name = write_results_name,
      overwrite = TRUE
    )
  }

  if (return_output) {
    return(df_out)
  }
  invisible(NULL)
}

#' Fit element-wise generalized additive models
#'
#'
#' @description
#' `ModelArray.gam` fits a generalized additive model at each requested
#' element in a \linkS4class{ModelArray} and returns a tibble of requested
#' model statistics. There is no model-level p-value for GAMs, so there is
#' no \code{correct.p.value.model} argument.
#'
#' @details
#' You may request returning specific statistical variables by setting
#' \code{var.*}, or you can get all by setting \code{full.outputs = TRUE}.
#' Note that statistics covered by \code{full.outputs} or \code{var.*} are
#' the ones from \code{broom::tidy()}, \code{broom::glance()}, and
#' \code{summary.gam()} only, and do not include corrected p-values.
#' However FDR-corrected p-values (\code{"fdr"}) are generated by default.
#'
#' List of acceptable statistic names for each of \code{var.*}:
#' \itemize{
#'   \item \code{var.smoothTerms}: \code{c("edf", "ref.df", "statistic",
#'     "p.value")}; From \code{broom::tidy(parametric = FALSE)}.
#'   \item \code{var.parametricTerms}: \code{c("estimate", "std.error",
#'     "statistic", "p.value")}; From \code{broom::tidy(parametric = TRUE)}.
#'   \item \code{var.model}: \code{c("adj.r.squared", "dev.expl",
#'     "sp.criterion", "scale", "df", "logLik", "AIC", "BIC", "deviance",
#'     "df.residual", "nobs")}; From \code{broom::glance()} and
#'     \code{\link[mgcv]{summary.gam}}.
#' }
#'
#' Smooth term names in the output are normalized: \code{s(age)} becomes
#' \code{s_age}, \code{ti(x,z)} becomes \code{ti_x_z}, and
#' \code{s(x):oFactor} becomes \code{s_x_BYoFactor}.
#'
#' For p-value corrections (arguments \code{correct.p.value.*}), supported
#' methods include all methods in \code{p.adjust.methods} except
#' \code{"none"}. You can request more than one method. FDR-corrected
#' p-values (\code{"fdr"}) are calculated by default. Turn it off by
#' setting to \code{"none"}.
#'
#' When \code{changed.rsq.term.index} is provided, a reduced model (dropping
#' the specified term) is fit at each element to compute delta adjusted
#' R-squared and partial R-squared. This approximately doubles execution
#' time per requested term. The term index refers to the position on the
#' right-hand side of \code{formula} (use \code{labels(terms(formula))} to
#' see the ordering).
#'
#' Arguments \code{num.subj.lthr.abs} and \code{num.subj.lthr.rel} are
#' mainly for input data with subject-specific masks, i.e. currently only
#' for volume data. For fixel-wise data, you may ignore these arguments.
#'
#' @inheritParams ModelArray.lm
#'
#' @param formula Formula (passed to \code{\link[mgcv]{gam}}).
#' @param var.smoothTerms Character vector. Statistics to save for smooth
#'   terms, from \code{broom::tidy(parametric = FALSE)}. See Details.
#' @param var.parametricTerms Character vector. Statistics to save for
#'   parametric terms, from \code{broom::tidy(parametric = TRUE)}.
#'   See Details.
#' @param var.model Character vector. Statistics to save for the overall
#'   model, from \code{broom::glance()} and
#'   \code{\link[mgcv]{summary.gam}}. See Details.
#' @param changed.rsq.term.index A list of positive integers. Each value
#'   is the index of a term on the right-hand side of \code{formula} for
#'   which delta adjusted R-squared and partial R-squared should be
#'   computed. Usually the term of interest is a smooth term or interaction
#'   term. Default \code{NULL} (not computed). See Details.
#' @param correct.p.value.smoothTerms Character vector. P-value
#'   correction method(s) for each smooth term. Default: \code{"fdr"}.
#'   See Details.
#' @param correct.p.value.parametricTerms Character vector. P-value
#'   correction method(s) for each parametric term. Default: \code{"fdr"}.
#'   See Details.
#' @param ... Additional arguments passed to \code{\link[mgcv]{gam}}
#'   (e.g. \code{method = "REML"}).
#'
#' @return A data.frame with one row per element. The first column is
#'   \code{element_id} (0-based). Remaining columns contain the requested
#'   statistics, named as \code{<term>.<statistic>} for per-term statistics
#'   and \code{model.<statistic>} for model-level statistics. Smooth term
#'   names are normalized (e.g. \code{s_age.statistic}). If p-value
#'   corrections were requested, additional columns are appended with the
#'   correction method as suffix (e.g. \code{s_age.p.value.fdr}). If
#'   \code{changed.rsq.term.index} was requested, additional columns
#'   \code{<term>.delta.adj.rsq} and \code{<term>.partial.rsq} are
#'   appended.
#'
#' @seealso \code{\link{ModelArray.lm}} for linear models,
#'   \code{\link{ModelArray.wrap}} for user-supplied functions,
#'   \code{\link{gen_gamFormula_fxSmooth}} and
#'   \code{\link{gen_gamFormula_contIx}} for formula helpers,
#'   \linkS4class{ModelArray} for the input class,
#'   \code{\link{ModelArray}} for the constructor,
#'   \code{\link{exampleElementData}} for testing formulas on a single
#'   element.
#'
#'
#' @examples{
#' \dontrun{
#' # Fit GAM with default outputs
#' results <- ModelArray.gam(
#'   FD ~ s(age, fx = TRUE) + sex,
#'   data = ma,
#'   phenotypes = phenotypes,
#'   scalar = "FD"
#' )
#' head(results)
#'
#' # With changed R-squared for the smooth term (term index 1)
#' results_rsq <- ModelArray.gam(
#'   FD ~ s(age, fx = TRUE) + sex,
#'   data = ma,
#'   phenotypes = phenotypes,
#'   scalar = "FD",
#'   changed.rsq.term.index = list(1)
#' )
#'
#' # Full outputs, no p-value correction
#' results_full <- ModelArray.gam(
#'   FD ~ s(age, fx = TRUE) + sex,
#'   data = ma,
#'   phenotypes = phenotypes,
#'   scalar = "FD",
#'   full.outputs = TRUE,
#'   correct.p.value.smoothTerms = "none",
#'   correct.p.value.parametricTerms = "none"
#' )
#' }
#' }
#'
#' @rdname ModelArray.gam
#' @export

ModelArray.gam <- function(formula, data, phenotypes, scalar = NULL, element.subset = NULL, full.outputs = FALSE,
                           var.smoothTerms = c("statistic", "p.value"),
                           var.parametricTerms = c("estimate", "statistic", "p.value"),
                           var.model = c("dev.expl"),
                           changed.rsq.term.index = NULL,
                           correct.p.value.smoothTerms = c("fdr"),
                           correct.p.value.parametricTerms = c("fdr"),
                           num.subj.lthr.abs = 10, num.subj.lthr.rel = 0.2,
                           verbose = TRUE, pbar = TRUE, n_cores = 1,
                           on_error = "stop",
                           write_results_name = NULL,
                           write_results_file = NULL,
                           write_results_flush_every = 1000L,
                           write_results_storage_mode = "double",
                           write_results_compression_level = 4L,
                           return_output = TRUE,
                           ...) {
  # Validation ----
  .validate_modelarray_input(data)

  if (is.null(scalar)){
    scalar <- .resolve_formula_scalar(formula, data, scalar)
  }

  element.subset <- .validate_element_subset(element.subset, data, scalar)
  phenotypes <- .align_phenotypes(data, phenotypes, scalar)

  # Build context ----
  ctx <- .build_gam_context(formula, data, phenotypes, scalar)

  # Use the cached breakdown for the formula checker display ----
  checker_gam_formula(formula, ctx$gam_formula_breakdown)

  # Display additional arguments ----
  dots <- list(...)
  dots_names <- names(dots)
  FUN <- mgcv::gam
  printAdditionalArgu(FUN, "method", dots)

  num.subj.lthr <- .compute_subject_threshold(phenotypes, num.subj.lthr.abs, num.subj.lthr.rel)

  # Full outputs override ----
  var.smoothTerms.full <- c("edf", "ref.df", "statistic", "p.value")
  var.parametricTerms.full <- c("estimate", "std.error", "statistic", "p.value")
  var.model.full <- c(
    "adj.r.squared", "dev.expl", "sp.criterion", "scale",
    "df", "logLik", "AIC", "BIC", "deviance", "df.residual", "nobs"
  )
  if (full.outputs == TRUE) {
    var.smoothTerms <- var.smoothTerms.full
    var.parametricTerms <- var.parametricTerms.full
    var.model <- var.model.full
  }

  var.smoothTerms <- var.smoothTerms[!duplicated(var.smoothTerms)]
  var.parametricTerms <- var.parametricTerms[!duplicated(var.parametricTerms)]
  var.model <- var.model[!duplicated(var.model)]

  if (length(var.smoothTerms) == 0 && length(var.parametricTerms) == 0 && length(var.model) == 0) {
    stop("All var.* arguments [var.smoothTerms, var.parametricTerms, var.model] are empty!")
  }

  for (var in var.smoothTerms) {
    if (!(var %in% var.smoothTerms.full)) {
      stop(paste0(var, " is not valid for var.smoothTerms!"))
    }
  }
  for (var in var.parametricTerms) {
    if (!(var %in% var.parametricTerms.full)) {
      stop(paste0(var, " is not valid for var.parametricTerms!"))
    }
  }
  for (var in var.model) {
    if (!(var %in% var.model.full)) {
      stop(paste0(var, " is not valid!"))
    }
  }

  # Changed.rsq setup ----
  # Changed.rsq setup ----
  var.model.orig <- var.model
  if (!is.null(changed.rsq.term.index)) {

    # Validation checks
    if (min(unlist(changed.rsq.term.index)) <= 0) {
      stop(
        "There is element(s) in changed.rsq.term.index <= 0. ",
        "It should be a (list of) positive integer!"
      )
    }

    terms.full.formula <- stats::terms(formula, keep.order = TRUE)

    if (max(unlist(changed.rsq.term.index)) > length(labels(terms.full.formula))) {
      stop(
        "Largest index in changed.rsq.term.index is more than the term number on the ",
        "right hand side of formula!"
      )
    }

    if (length(labels(terms.full.formula)) == 0) {
      stop(
        "Trying to analyze changed.rsq but there is no variable (except intercept 1) ",
        "on right hand side of formula! Please provide at least one valid variable."
      )
    }

    changed.rsq.term.fullFormat.list <- labels(terms.full.formula)[unlist(changed.rsq.term.index)]

    # Compute short format names: s(age) -> s_age, ti(x,z) -> ti_x_z, etc.
    changed.rsq.term.shortFormat.list <- list()
    for (changed.rsq.term.fullFormat in changed.rsq.term.fullFormat.list) {
      temp <- strsplit(changed.rsq.term.fullFormat, "[(]")[[1]]
      if (length(temp) == 1) {
        # Not a smooth term — no parentheses
        str_valid <- changed.rsq.term.fullFormat
      } else {
        smooth.class <- temp[1]
        theEval <- eval(parse(text = changed.rsq.term.fullFormat))
        str_valid <- paste0(
          smooth.class, "_",
          paste(theEval$term, collapse = "_")
        )
        if (theEval$by != "NA") {
          str_valid <- paste0(str_valid, "_BY", theEval$by)
        }
      }
      changed.rsq.term.shortFormat.list <- append(
        changed.rsq.term.shortFormat.list, str_valid
      )
    }

    message(
      "will get changed R-squared (delta.adj.rsq and partial.rsq) ",
      "so the execution time will be longer."
    )

    if (!("adj.r.squared" %in% var.model)) {
      var.model <- c(var.model, "adj.r.squared")
    }
    flag_sse <- TRUE
  } else {
    flag_sse <- FALSE
  }

  # p-value correction checks ----
  check_validity_correctPValue(
    correct.p.value.smoothTerms, "correct.p.value.smoothTerms",
    var.smoothTerms, "var.smoothTerms"
  )
  check_validity_correctPValue(
    correct.p.value.parametricTerms, "correct.p.value.parametricTerms",
    var.parametricTerms, "var.parametricTerms"
  )

  # Start the model fitting ----
  if (verbose) {
    message(glue::glue("Fitting element-wise GAMs for {scalar}"))
    message(glue::glue("initiating...."))
  }

  num.elements.total <- numElementsTotal(modelarray = data, scalar_name = scalar)

  # Initiate using ctx ----
  init_args <- list(
    ctx = ctx,
    var.smoothTerms = var.smoothTerms,
    var.parametricTerms = var.parametricTerms,
    var.model = var.model,
    num.subj.lthr = num.subj.lthr,
    flag_sse = flag_sse,
    on_error = on_error, ...
  )
  initiator <- .find_initiator_element(
    analyseOneElement.gam, num.elements.total, init_args, verbose
  )
  i_element_success_initiate <- initiator$i_element
  column_names <- initiator$outputs$column_names
  list.smoothTerms <- initiator$outputs$list.smoothTerms
  list.parametricTerms <- initiator$outputs$list.parametricTerms
  num.stat.output <- length(column_names)

  if (verbose) {
    message(glue::glue("looping across elements...."))
  }

  need_smooth_correction <- (!all(correct.p.value.smoothTerms == "none")) &&
    ("p.value" %in% var.smoothTerms)
  need_param_correction <- (!all(correct.p.value.parametricTerms == "none")) &&
    ("p.value" %in% var.parametricTerms)
  need_changed_rsq <- !is.null(changed.rsq.term.index)
  need_full_df <- return_output || need_smooth_correction || need_param_correction || need_changed_rsq
  if (!return_output && (need_smooth_correction || need_param_correction || need_changed_rsq)) {
    stop("return_output=FALSE is not supported when p-value correction or changed.rsq is requested")
  }

  # Initialize stream writer ----
  writer <- .init_results_stream_writer(
    write_results_name = write_results_name,
    write_results_file = write_results_file,
    n_rows = length(element.subset),
    column_names = column_names,
    flush_every = write_results_flush_every,
    storage_mode = write_results_storage_mode,
    compression_level = write_results_compression_level
  )

  # Start model looping ----
  fits_all <- if (need_full_df) vector("list", length(element.subset)) else NULL
  chunk_size <- if (is.null(writer)) length(element.subset) else as.integer(write_results_flush_every)
  chunk_starts <- seq(1L, length(element.subset), by = chunk_size)

  for (chunk_start in chunk_starts) {
    chunk_end <- min(chunk_start + chunk_size - 1L, length(element.subset))
    chunk_elements <- element.subset[chunk_start:chunk_end]

    # Main loop passes ctx
    chunk_fits <- .parallel_dispatch(
      chunk_elements, analyseOneElement.gam, n_cores, pbar,
      ctx = ctx,
      var.smoothTerms = var.smoothTerms,
      var.parametricTerms = var.parametricTerms,
      var.model = var.model,
      num.subj.lthr = num.subj.lthr,
      num.stat.output = num.stat.output,
      flag_initiate = FALSE, flag_sse = flag_sse,
      on_error = on_error, ...
    )

    if (need_full_df) {
      fits_all[chunk_start:chunk_end] <- chunk_fits
    }
    if (!is.null(writer)) {
      chunk_df <- as.data.frame(do.call(rbind, chunk_fits))
      colnames(chunk_df) <- column_names
      writer <- .results_stream_write_block(writer, chunk_df)
    }
  }
  .finalize_results_stream_writer(writer)

  if (!need_full_df) {
    return(invisible(NULL))
  }

  result_mat <- do.call(rbind, fits_all)
  col_list <- lapply(seq_len(ncol(result_mat)), function(j) result_mat[, j])
  names(col_list) <- column_names
  df_out <- cheapr::fast_df(.args = col_list)

  # P-value corrections ----
  df_out <- .correct_pvalues(df_out, list.smoothTerms, correct.p.value.smoothTerms, var.smoothTerms)
  df_out <- .correct_pvalues(df_out, list.parametricTerms, correct.p.value.parametricTerms, var.parametricTerms)

  # Compute changed R-squared ----
  if (need_changed_rsq) {
    terms.full.formula <- stats::terms(formula, keep.order = TRUE)

    for (i.changed.rsq.term in seq_along(changed.rsq.term.index)) {
      idx.changed.rsq.term <- changed.rsq.term.index[[i.changed.rsq.term]]
      changed.rsq.term.fullFormat <- changed.rsq.term.fullFormat.list[i.changed.rsq.term]
      changed.rsq.term.shortFormat <- changed.rsq.term.shortFormat.list[[i.changed.rsq.term]][1]

      if (length(labels(terms.full.formula)) == 1) {
        temp <- toString(formula) %>% strsplit("[, ]")
        reduced.formula <- stats::as.formula(paste0(temp[[1]][3], "~1"))
      } else {
        reduced.formula <- formula(
          stats::drop.terms(terms.full.formula, idx.changed.rsq.term, keep.response = TRUE)
        )
      }

      message(
        "* Getting changed R-squared for term: ",
        changed.rsq.term.fullFormat,
        " via reduced model; will show up as ",
        changed.rsq.term.shortFormat,
        " in final dataframe"
      )
      print(reduced.formula)

      ## Build a separate context for the reduced model ----
      reduced_ctx <- .build_gam_context(reduced.formula, data, phenotypes, scalar)

      reduced.model.outputs_initiator <- analyseOneElement.gam(
        i_element = i_element_success_initiate,
        ctx = reduced_ctx,
        var.smoothTerms = c(), var.parametricTerms = c(),
        var.model = c("adj.r.squared"),
        num.subj.lthr = num.subj.lthr, num.stat.output = NULL,
        flag_initiate = TRUE, flag_sse = TRUE,
        ...
      )
      reduced.model.column_names <- reduced.model.outputs_initiator$column_names
      reduced.model.num.stat.output <- length(reduced.model.column_names)

      reduced.model.fits <- .parallel_dispatch(
        element.subset, analyseOneElement.gam, n_cores, pbar,
        ctx = reduced_ctx,
        var.smoothTerms = c(), var.parametricTerms = c(),
        var.model = c("adj.r.squared"),
        num.subj.lthr = num.subj.lthr,
        num.stat.output = reduced.model.num.stat.output,
        flag_initiate = FALSE, flag_sse = TRUE,
        ...
      )

      result_mat_reduced <- do.call(rbind, reduced.model.fits)
      col_list_reduced <- lapply(
        seq_len(ncol(result_mat_reduced)),
        function(j) result_mat_reduced[, j]
      )
      names(col_list_reduced) <- reduced.model.column_names
      reduced.model.df_out <- cheapr::fast_df(.args = col_list_reduced)

      ## Compute delta adj R-sq and partial R-sq ----
      delta_col <- paste0(changed.rsq.term.shortFormat, ".delta.adj.rsq")
      partial_col <- paste0(changed.rsq.term.shortFormat, ".partial.rsq")

      df_out[[delta_col]] <- df_out[["model.adj.r.squared"]] -
        reduced.model.df_out[["model.adj.r.squared"]]

      full_sse <- df_out[["model.sse"]]
      reduced_sse <- reduced.model.df_out[["model.sse"]]
      df_out[[partial_col]] <- (reduced_sse - full_sse) / reduced_sse
    }

    # if adjusted r sq is not requested (see var.model.orig), remove it:
    if (!("adj.r.squared" %in% var.model.orig)) {
      df_out <- df_out[, colnames(df_out) != "model.adj.r.squared", drop = FALSE]
    }

    # remove full model's sse (model.sse):
    df_out <- df_out[, colnames(df_out) != "model.sse", drop = FALSE]
  }

  # Rewrite if corrections applied and streaming was used ----
  if (!is.null(writer) && (need_smooth_correction || need_param_correction || need_changed_rsq)) {
    writeResults(
      fn.output = write_results_file,
      df.output = df_out,
      analysis_name = write_results_name,
      overwrite = TRUE
    )
  }

  if (return_output) {
    return(df_out)
  }
  invisible(NULL)
}

#' Run a user-supplied function for element-wise data
#'
#' @description
#' `ModelArray.wrap` runs a user-supplied function \code{FUN} at each
#' requested element and returns a tibble of results combined across
#' elements.
#'
#' @details
#' This provides a generic framework reusing ModelArray's per-element
#' looping, alignment, subject-thresholding, and parallelization. The user
#' function is called as \code{FUN(data = dat, ...)} where \code{dat} is
#' \code{phenotypes} with all scalar columns appended for the current
#' element. The return value from \code{FUN} for a single element must be
#' one of:
#' \itemize{
#'   \item a one-row \code{data.frame} or \code{tibble}
#'   \item a named list
#'   \item a named atomic vector
#' }
#' The column names from the first successful element determine the final
#' schema.
#'
#' Note: \code{ModelArray.wrap} never performs any p-value corrections or
#' modifications. If you need adjusted p-values (e.g. FDR), implement
#' them inside \code{FUN}.
#'
#' Use \code{\link{exampleElementData}} to construct a sample per-element
#' data.frame for testing your function before committing to a full run.
#'
#' @inheritParams ModelArray.lm
#'
#' @param FUN A function that accepts at least \code{data} (a data.frame)
#'   and returns a one-row data.frame/tibble, a named list, or a named
#'   vector of results for that element.
#' @param write_scalar_name Optional character. If provided, selected
#'   output columns are written into
#'   \code{scalars/<write_scalar_name>/values} in the HDF5 file specified
#'   by \code{write_scalar_file}.
#' @param write_scalar_file Optional character. HDF5 output file path.
#'   Required when \code{write_scalar_name} is provided.
#' @param write_scalar_columns Optional character or integer vector
#'   selecting which output columns to save as scalar values. If
#'   \code{NULL} (default), uses all output columns except
#'   \code{element_id}.
#' @param write_scalar_column_names Optional character vector of source
#'   names saved as scalar \code{column_names}. If \code{NULL}, uses
#'   \code{phenotypes$source_file}.
#' @param write_scalar_flush_every Positive integer. Elements per write
#'   block for scalar writes. Default 1000.
#' @param write_scalar_storage_mode Character. Storage mode for scalar
#'   writes (e.g. \code{"double"}). Default \code{"double"}.
#' @param write_scalar_compression_level Integer 0--9. Gzip compression
#'   level for scalar writes. Default 4.
#' @param ... Additional arguments forwarded to \code{FUN}.
#'
#' @return If \code{flag_initiate = TRUE}, a list with one component:
#'   \describe{
#'     \item{column_names}{Character vector. The column names derived from
#'       the return value of \code{user_fun}, with \code{"element_id"}
#'       prepended. For unnamed list or atomic returns, columns are named
#'       \code{v1}, \code{v2}, etc. Set to \code{NaN} if the element was
#'       skipped or errored.}
#'   }
#'   If \code{flag_initiate = FALSE}, a numeric vector of length
#'   \code{num.stat.output} with \code{element_id} (0-based) first and
#'   the coerced output of \code{user_fun} in subsequent positions.
#'   All-\code{NaN} (except \code{element_id}) if the element was skipped
#'   or if an error occurred with \code{on_error = "skip"}.
#'
#' @seealso \code{\link{ModelArray.lm}} for linear models,
#'   \code{\link{ModelArray.gam}} for GAMs,
#'   \code{\link{exampleElementData}} for building test data,
#'   \linkS4class{ModelArray} for the input class.
#'
#' @examples{
#' \dontrun{
#' ma <- ModelArray("path/to/data.h5", scalar_types = c("FD"))
#' phenotypes <- read.csv("cohort.csv")
#'
#' # Simple custom function
#' my_fun <- function(data, ...) {
#'   mod <- lm(FD ~ age + sex, data = data)
#'   tidy_out <- broom::tidy(mod)
#'   # Return a one-row tibble
#'   tibble::tibble(
#'     age_estimate = tidy_out$estimate[tidy_out$term == "age"],
#'     age_pvalue   = tidy_out$p.value[tidy_out$term == "age"]
#'   )
#' }
#'
#'
#' # Test on one element first
#' test_df <- exampleElementData(ma, scalar = "FD",
#'                                i_element = 1,
#'                                phenotypes = phenotypes)
#' my_fun(data = test_df)
#'
#' # Run across all elements
#' results <- ModelArray.wrap(
#'   FUN = my_fun,
#'   data = ma,
#'   phenotypes = phenotypes,
#'   scalar = "FD"
#' )
#' }
#' }
#'
#' @rdname ModelArray.wrap
#' @export
ModelArray.wrap <- function(FUN, data, phenotypes, scalar, element.subset = NULL,
                            num.subj.lthr.abs = 10, num.subj.lthr.rel = 0.2,
                            verbose = TRUE, pbar = TRUE, n_cores = 1,
                            on_error = "stop",
                            write_scalar_name = NULL,
                            write_scalar_file = NULL,
                            write_scalar_columns = NULL,
                            write_scalar_column_names = NULL,
                            write_scalar_flush_every = 1000L,
                            write_scalar_storage_mode = "double",
                            write_scalar_compression_level = 4L,
                            write_results_name = NULL,
                            write_results_file = NULL,
                            write_results_flush_every = 1000L,
                            write_results_storage_mode = "double",
                            write_results_compression_level = 4L,
                            return_output = TRUE,
                            ...) {
  # Validation ----
  .validate_modelarray_input(data)
  element.subset <- .validate_element_subset(element.subset, data, scalar)
  phenotypes <- .align_phenotypes(data, phenotypes, scalar)
  num.subj.lthr <- .compute_subject_threshold(phenotypes, num.subj.lthr.abs, num.subj.lthr.rel)

  # Build context ----
  ctx <- .build_wrap_context(data, phenotypes, scalar)

  # Start model fitting ----
  if (verbose) {
    message(glue::glue("Running element-wise user function for {scalar}"))
    message(glue::glue("initiating...."))
  }

  num.elements.total <- numElementsTotal(modelarray = data, scalar_name = scalar)

  # Initiate using ctx ----
  init_args <- list(
    user_fun = FUN,
    ctx = ctx,
    num.subj.lthr = num.subj.lthr,
    on_error = on_error, ...
  )
  initiator <- .find_initiator_element(
    analyseOneElement.wrap, num.elements.total, init_args, verbose
  )
  column_names <- initiator$outputs$column_names
  num.stat.output <- length(column_names)

  if (verbose) message(glue::glue("looping across elements...."))

  # Initialize stream writer ----
  writer_results <- .init_results_stream_writer(
    write_results_name = write_results_name,
    write_results_file = write_results_file,
    n_rows = length(element.subset),
    column_names = column_names,
    flush_every = write_results_flush_every,
    storage_mode = write_results_storage_mode,
    compression_level = write_results_compression_level
  )

  writing_scalar <- !is.null(write_scalar_name)
  if (writing_scalar) {
    if (!is.character(write_scalar_name) || length(write_scalar_name) != 1L || write_scalar_name == "") {
      stop("write_scalar_name must be a non-empty character string when provided")
    }
    if (is.null(write_scalar_file) || !is.character(write_scalar_file) || length(write_scalar_file) != 1L) {
      stop("write_scalar_file must be a single character path when write_scalar_name is provided")
    }
    if (!is.numeric(write_scalar_flush_every) || length(write_scalar_flush_every) != 1L || write_scalar_flush_every <= 0) {
      stop("write_scalar_flush_every must be a positive integer")
    }
    write_scalar_flush_every <- as.integer(write_scalar_flush_every)

    if (is.null(write_scalar_columns)) {
      write_scalar_columns <- setdiff(column_names, "element_id")
    }

    if (is.character(write_scalar_columns)) {
      missing_cols <- setdiff(write_scalar_columns, column_names)
      if (length(missing_cols) > 0L) {
        stop("write_scalar_columns not found in wrap output: ", paste(missing_cols, collapse = ", "))
      }
      scalar_col_idx <- match(write_scalar_columns, column_names)
    } else {
      scalar_col_idx <- as.integer(write_scalar_columns)
    }

    if (is.null(write_scalar_column_names)) {
      write_scalar_column_names <- column_names[scalar_col_idx]
    }
    if (length(write_scalar_column_names) != length(scalar_col_idx)) {
      stop("length(write_scalar_column_names) must equal number of selected write_scalar_columns")
    }

    # Initialize scalar output dataset
    if (!file.exists(write_scalar_file)) {
      rhdf5::h5createFile(write_scalar_file)
    }
    scalar_grp <- paste0("scalars/", write_scalar_name)
    h5_write <- hdf5r::H5File$new(write_scalar_file, mode = "a")
    if (!h5_write$exists("scalars")) {
      h5_write$create_group("scalars")
    }
    scalars_grp_obj <- h5_write$open("scalars")
    if (scalars_grp_obj$exists(write_scalar_name)) {
      scalars_grp_obj$link_delete(write_scalar_name)
    }
    scalars_grp_obj$create_group(write_scalar_name)
    h5_write$close_all()

    dataset_path <- paste0(scalar_grp, "/values")
    chunk_rows <- min(write_scalar_flush_every, length(element.subset))
    rhdf5::h5createDataset(
      file = write_scalar_file,
      dataset = dataset_path,
      dims = c(length(element.subset), length(scalar_col_idx)),
      storage.mode = write_scalar_storage_mode,
      chunk = c(chunk_rows, length(scalar_col_idx)),
      level = as.integer(write_scalar_compression_level)
    )
  }

  # Start model looping ----
  fits_all <- if (return_output) vector("list", length(element.subset)) else NULL
  write_row_cursor <- 1L

  chunk_size <- length(element.subset)
  if (writing_scalar) {
    chunk_size <- min(chunk_size, write_scalar_flush_every)
  }
  if (!is.null(writer_results)) {
    chunk_size <- min(chunk_size, as.integer(write_results_flush_every))
  }
  chunk_starts <- seq(1L, length(element.subset), by = chunk_size)

  for (chunk_start in chunk_starts) {
    chunk_end <- min(chunk_start + chunk_size - 1L, length(element.subset))
    chunk_elements <- element.subset[chunk_start:chunk_end]

    ## Main loop passes ctx ----
    chunk_fits <- .parallel_dispatch(
      chunk_elements, analyseOneElement.wrap, n_cores, pbar,
      user_fun = FUN,
      ctx = ctx,
      num.subj.lthr = num.subj.lthr,
      num.stat.output = num.stat.output,
      flag_initiate = FALSE, on_error = on_error,
      ...
    )

    if (return_output) {
      fits_all[chunk_start:chunk_end] <- chunk_fits
    }

    chunk_df <- NULL
    if (!is.null(writer_results) || writing_scalar) {
      chunk_df <- as.data.frame(do.call(rbind, chunk_fits))
      colnames(chunk_df) <- column_names
    }
    if (!is.null(writer_results)) {
      writer_results <- .results_stream_write_block(writer_results, chunk_df)
    }

    if (writing_scalar) {
      block <- as.matrix(chunk_df[, scalar_col_idx, drop = FALSE])
      row_idx <- write_row_cursor:(write_row_cursor + nrow(block) - 1L)
      rhdf5::h5write(
        obj = block,
        file = write_scalar_file,
        name = dataset_path,
        index = list(row_idx, seq_len(ncol(block)))
      )
      write_row_cursor <- write_row_cursor + nrow(block)
    }
  }

  # Finalize H5 writing ----
  if (writing_scalar) {
    rhdf5::h5writeAttribute(
      attr = write_scalar_column_names,
      h5obj = write_scalar_file,
      name = "column_names",
      h5loc = dataset_path
    )
    rhdf5::h5write(
      obj = write_scalar_column_names,
      file = write_scalar_file,
      name = paste0("scalars/", write_scalar_name, "/column_names")
    )
    rhdf5::h5closeAll()
  }
  .finalize_results_stream_writer(writer_results)

  if (!return_output) {
    return(invisible(NULL))
  }

  # Better proposed change:
  result_mat <- do.call(rbind, fits_all)
  col_list <- lapply(seq_len(ncol(result_mat)), function(j) result_mat[, j])
  names(col_list) <- column_names
  df_out <- cheapr::fast_df(.args = col_list)
  df_out
}
